<a href="https://colab.research.google.com/github/Snowdenstyll/keno/blob/main/DailyGrand.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv("/content/2023.csv")

In [ ]:
df.head()

PlayDate  N01  N02  N03  N04  N05  N06
0  2023-01-02    2   19   20   27   47    5
1  2023-01-05    1   27   32   33   35    4
2  2023-01-09    5   13   15   22   45    6
3  2023-01-12    4    7   27   33   48    7
4  2023-01-16   14   19   21   36   48    1

In [ ]:
df.tail()

PlayDate  N01  N02  N03  N04  N05  N06
91  2023-11-16    5   27   30   41   42    2
92  2023-11-20    3   36   38   42   48    6
93  2023-11-23    1   12   14   20   31    4
94  2023-11-27   13   16   18   27   30    6
95  2023-11-30   31   32   34   39   49    6

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   PlayDate  96 non-null     object
 1   N01       96 non-null     int64 
 2   N02       96 non-null     int64 
 3   N03       96 non-null     int64 
 4   N04       96 non-null     int64 
 5   N05       96 non-null     int64 
 6   N06       96 non-null     int64 
dtypes: int64(6), object(1)
memory usage: 5.4+ KB


In [ ]:
df.describe()

N01        N02        N03        N04       N05        N06
count  96.000000  96.000000  96.000000  96.000000  96.00000  96.000000
mean    7.822917  16.135417  23.083333  31.895833  40.87500   4.270833
std     6.296189   7.730486   7.842753   8.036075   7.18368   2.002520
min     1.000000   2.000000   8.000000  13.000000  20.00000   1.000000
25%     3.000000  10.000000  17.000000  26.750000  37.00000   2.000000
50%     6.000000  15.000000  23.000000  33.000000  43.00000   5.000000
75%    12.250000  21.000000  28.000000  38.000000  47.00000   6.000000
max    31.000000  39.000000  44.000000  47.000000  49.00000   7.000000

In [ ]:
df.drop(['PlayDate'], axis=1, inplace=True)

In [ ]:
df.head()

N01  N02  N03  N04  N05  N06
0    2   19   20   27   47    5
1    1   27   32   33   35    4
2    5   13   15   22   45    6
3    4    7   27   33   48    7
4   14   19   21   36   48    1

In [ ]:
scaler = StandardScaler().fit(df.values)
transformed_dataset = scaler.transform(df.values)
transformed_df = pd.DataFrame(data=transformed_dataset, index=df.index)

In [ ]:
transformed_df.head()

0         1         2         3         4         5
0 -0.929687  0.372502 -0.395208 -0.612430  0.857103  0.366036
1 -1.089347  1.412798  1.142899  0.138123 -0.822119 -0.135956
2 -0.450707 -0.407720 -1.036086 -1.237890  0.577232  0.868028
3 -0.610367 -1.187942  0.502021  0.138123  0.997038  1.370020
4  0.986233  0.372502 -0.267032  0.513399  0.997038 -1.641932

In [ ]:
# All our games
number_of_rows = df.values.shape[0]
number_of_rows

96

In [ ]:
# Amount of games we need to take into consideration for prediction
window_length = 4
window_length

4

In [ ]:
# Balls counts
number_of_features = df.values.shape[1]
number_of_features

6

In [ ]:
X = np.empty([ number_of_rows - window_length, window_length, number_of_features], dtype=float)
X

array([[[4.88973893e-310, 4.88973926e-310, 4.88973893e-310,
         4.88973926e-310, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 6.62169433e-310,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 4.88971490e-310, 0.00000000e+000],
        [3.95252517e-323, 4.82411404e-311, 3.95252517e-323,
         4.88973894e-310, 0.00000000e+000, 4.88973894e-310]],

       [[4.88973871e-310, 6.62169437e-310, 0.00000000e+000,
         0.00000000e+000, 4.88971490e-310, 0.00000000e+000],
        [4.88973895e-310, 1.38338381e-322, 4.88973876e-310,
         0.00000000e+000, 9.88131292e-324, 4.94065646e-324],
        [3.95252517e-322, 4.88973876e-310, 1.58101007e-321,
         2.37151510e-322, 4.89050815e-310, 2.32210854e-322],
        [2.32210854e-322, 4.88973875e-310, 1.81816158e-321,
         3.95252517e-322, 4.89050814e-310, 0.00000000e+000]],

       [[0.00000000e+000, 0.

In [ ]:
y = np.empty([ number_of_rows - window_length, number_of_features], dtype=float)
y

array([[6.62176051e-310, 4.88973871e-310, 4.88973875e-310,
        4.88973871e-310, 4.94065646e-324, 4.88973915e-310],
       [4.88973915e-310, 4.94065646e-324, 4.88973915e-310,
        4.88973915e-310, 1.13088618e-042, 6.62176016e-310],
       [4.66449677e-033, 0.00000000e+000, 4.94065646e-324,
        2.12199579e-314, 6.12743388e-154, 6.62175947e-310],
       [4.94065646e-324, 2.12199579e-314, 8.48798316e-314,
        1.27319747e-313, 1.39804304e-076, 4.88973915e-310],
       [6.62176016e-310, 2.12199579e-314, 8.48798316e-314,
        2.54639495e-313, 4.94065646e-324, 4.88973915e-310],
       [4.88973915e-310, 9.88131292e-324, 4.88973915e-310,
        4.88973915e-310, 4.88973915e-310, 4.88971490e-310],
       [6.62169451e-310, 4.88971490e-310, 1.21089413e-099,
        3.18299369e-313, 6.15378779e-313, 4.88971490e-310],
       [6.62169494e-310, 4.94065646e-324, 1.39803645e-076,
        6.79038653e-313, 9.54898106e-313, 6.01346930e-154],
       [4.88973915e-310, 1.27319747e-313, 4.8897

In [ ]:
for i in range(0, number_of_rows-window_length):
    X[i] = transformed_df.iloc[i : i+window_length, 0 : number_of_features]
    y[i] = transformed_df.iloc[i+window_length : i+window_length+1, 0 : number_of_features]

In [ ]:
X.shape

(92, 4, 6)

In [ ]:
y.shape

(92, 6)

In [ ]:
X[0]

array([[-0.92968673,  0.37250188, -0.39520803, -0.61242997,  0.85710279,
         0.3660359 ],
       [-1.08934671,  1.41279803,  1.14289891,  0.1381225 , -0.822119  ,
        -0.13595619],
       [-0.45070681, -0.40772024, -1.03608593, -1.23789036,  0.57723249,
         0.868028  ],
       [-0.61036678, -1.18794235,  0.50202102,  0.1381225 ,  0.99703794,
         1.37002009]])

In [ ]:
X[1]

array([[-1.08934671,  1.41279803,  1.14289891,  0.1381225 , -0.822119  ,
        -0.13595619],
       [-0.45070681, -0.40772024, -1.03608593, -1.23789036,  0.57723249,
         0.868028  ],
       [-0.61036678, -1.18794235,  0.50202102,  0.1381225 ,  0.99703794,
         1.37002009],
       [ 0.98623298,  0.37250188, -0.26703245,  0.51339874,  0.99703794,
        -1.64193247]])

In [ ]:
y[0]

array([ 0.98623298,  0.37250188, -0.26703245,  0.51339874,  0.99703794,
       -1.64193247])

In [ ]:
y[1]

array([-0.13138686, -0.92786831, -0.0106813 ,  0.26321458,  0.29736219,
        0.3660359 ])

In [ ]:
# Recurrent Neural Netowrk (RNN) with Long Short Term Memory (LSTM)
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, Dropout
batch_size = 100

In [ ]:
# Initialising the RNN
model = Sequential()
# Adding the input layer and the LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a first Dropout layer
model.add(Dropout(0.2))
# Adding a second LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a second Dropout layer
model.add(Dropout(0.2))
# Adding a third LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a fourth LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = False)))
# Adding a fourth Dropout layer
model.add(Dropout(0.2))
# Adding the first output layer
model.add(Dense(70))
# Adding the last output layer
model.add(Dense(number_of_features))

In [ ]:
from tensorflow import keras
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.0001), loss ='mse', metrics=['accuracy'])

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9, random_state=90)

# Train the model
#history = model.fit(X_train, y_train, batch_size=100, epochs=400, verbose=2)
history = model.fit(X_train, y_train, batch_size=15, epochs=300, verbose=2)


Epoch 1/300
1/1 - 22s - loss: 1.3504 - accuracy: 0.1111 - 22s/epoch - 22s/step
Epoch 2/300
1/1 - 0s - loss: 1.3460 - accuracy: 0.3333 - 20ms/epoch - 20ms/step
Epoch 3/300
1/1 - 0s - loss: 1.3412 - accuracy: 0.3333 - 20ms/epoch - 20ms/step
Epoch 4/300
1/1 - 0s - loss: 1.3361 - accuracy: 0.3333 - 19ms/epoch - 19ms/step
Epoch 5/300
1/1 - 0s - loss: 1.3293 - accuracy: 0.3333 - 17ms/epoch - 17ms/step
Epoch 6/300
1/1 - 0s - loss: 1.3240 - accuracy: 0.4444 - 21ms/epoch - 21ms/step
Epoch 7/300
1/1 - 0s - loss: 1.3173 - accuracy: 0.5556 - 18ms/epoch - 18ms/step
Epoch 8/300
1/1 - 0s - loss: 1.3104 - accuracy: 0.5556 - 18ms/epoch - 18ms/step
Epoch 9/300
1/1 - 0s - loss: 1.3021 - accuracy: 0.5556 - 24ms/epoch - 24ms/step
Epoch 10/300
1/1 - 0s - loss: 1.2970 - accuracy: 0.5556 - 17ms/epoch - 17ms/step
Epoch 11/300
1/1 - 0s - loss: 1.2905 - accuracy: 0.5556 - 16ms/epoch - 16ms/step
Epoch 12/300
1/1 - 0s - loss: 1.2810 - accuracy: 0.5556 - 19ms/epoch - 19ms/step
Epoch 13/300
1/1 - 0s - loss: 1.2718 -

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=2)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

3/3 - 3s - loss: 2.2181 - accuracy: 0.1807 - 3s/epoch - 846ms/step
Test Loss: 2.2181451320648193, Test Accuracy: 0.1807228922843933


In [ ]:
#history = model.fit(X_train, y_train, batch_size=50, epochs=100, verbose=2)
history = model.fit(X_train, y_train, batch_size=50, epochs=100, verbose=2)

Epoch 1/100
1/1 - 0s - loss: 0.0080 - accuracy: 0.8889 - 19ms/epoch - 19ms/step
Epoch 2/100
1/1 - 0s - loss: 0.0140 - accuracy: 0.8889 - 18ms/epoch - 18ms/step
Epoch 3/100
1/1 - 0s - loss: 0.0076 - accuracy: 1.0000 - 18ms/epoch - 18ms/step
Epoch 4/100
1/1 - 0s - loss: 0.0095 - accuracy: 0.8889 - 16ms/epoch - 16ms/step
Epoch 5/100
1/1 - 0s - loss: 0.0130 - accuracy: 0.8889 - 18ms/epoch - 18ms/step
Epoch 6/100
1/1 - 0s - loss: 0.0141 - accuracy: 0.8889 - 18ms/epoch - 18ms/step
Epoch 7/100
1/1 - 0s - loss: 0.0094 - accuracy: 0.8889 - 24ms/epoch - 24ms/step
Epoch 8/100
1/1 - 0s - loss: 0.0130 - accuracy: 0.8889 - 18ms/epoch - 18ms/step
Epoch 9/100
1/1 - 0s - loss: 0.0147 - accuracy: 0.8889 - 17ms/epoch - 17ms/step
Epoch 10/100
1/1 - 0s - loss: 0.0065 - accuracy: 1.0000 - 16ms/epoch - 16ms/step
Epoch 11/100
1/1 - 0s - loss: 0.0094 - accuracy: 0.7778 - 17ms/epoch - 17ms/step
Epoch 12/100
1/1 - 0s - loss: 0.0111 - accuracy: 0.8889 - 20ms/epoch - 20ms/step
Epoch 13/100
1/1 - 0s - loss: 0.0100 

In [ ]:
df1 = df.copy()
to_predict = df.tail(3)
to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)
to_predict

<ipython-input-98-a91c54494079>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)


N01  N02  N03  N04  N05  N06
93    1   12   14   20   31    4
94   13   16   18   27   30    6

In [ ]:
to_predict = np.array(to_predict)
to_predict

array([[ 1, 12, 14, 20, 31,  4],
       [13, 16, 18, 27, 30,  6]])

In [ ]:
scaled_to_predict = scaler.transform(to_predict)

In [ ]:
y_pred = model.predict(np.array([scaled_to_predict]))
print("The predicted numbers in the last lottery game are:", scaler.inverse_transform(y_pred).astype(int)[0])

1/1 [==============================] - 5s 5s/step
The predicted numbers in the last lottery game are: [ 6 15 23 31 43  4]


In [ ]:
prediction = df.tail(1)
prediction = np.array(prediction)
print("The actual numbers in the last lottery game were:", prediction[0])

The actual numbers in the last lottery game were: [31 32 34 39 49  6]


In [ ]:
temp = np.array(scaler.inverse_transform(y_pred).astype(int)[0])
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("winners:", duplicates)
print(len(duplicates)/20)

winners: [ 6 31]
0.1


# Predict the next set of numbers

In [ ]:
next = df.copy()
next = next.tail((window_length))
next

N01  N02  N03  N04  N05  N06
92    3   36   38   42   48    6
93    1   12   14   20   31    4
94   13   16   18   27   30    6
95   31   32   34   39   49    6

In [ ]:
next = np.array(next)
next

array([[ 3, 36, 38, 42, 48,  6],
       [ 1, 12, 14, 20, 31,  4],
       [13, 16, 18, 27, 30,  6],
       [31, 32, 34, 39, 49,  6]])

In [ ]:
x_next = scaler.transform(next)
x_next

next_Date = '2023-12-01 Evening';

In [ ]:
y_next_pred = model.predict(np.array([x_next]))
print("The predicted numbers for the lottery game which will take place on",next_Date, "are (without rounding up):\n", scaler.inverse_transform(y_next_pred).astype(int)[0])

print("\n")
temp = np.array(scaler.inverse_transform(y_next_pred).astype(int)[0])
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("without rounding up")
print("winners:", duplicates)
print(len(duplicates)/20)

1/1 [==============================] - 3s 3s/step
The predicted numbers for the lottery game which will take place on 2023-12-01 Evening are (without rounding up):
 [31 32 34 37 53  5]


without rounding up
winners: [31 32 34]
0.15


In [ ]:
y_next_pred = model.predict(np.array([x_next]))
print("The predicted numbers for the lottery game which will take place on",next_Date, "are (with rounding up):\n", scaler.inverse_transform(y_next_pred).astype(int)[0]+1)

1/1 [==============================] - 0s 25ms/step
The predicted numbers for the lottery game which will take place on 2023-12-01 Evening are (with rounding up):
 [32 33 35 38 54  6]


In [ ]:
temp = np.array(scaler.inverse_transform(y_next_pred).astype(int)[0]+1)
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("with rounding up")
print("winners:", duplicates)
print(len(duplicates)/20)

with rounding up
winners: [ 6 32]
0.1


In [ ]:
to_predict_next = df.tail(3)
to_predict_next = np.array(to_predict_next)
to_predict_next

array([[ 1, 12, 14, 20, 31,  4],
       [13, 16, 18, 27, 30,  6],
       [31, 32, 34, 39, 49,  6]])

In [ ]:
scaled_to_predict_next = scaler.transform(to_predict_next)
y_pred_next = model.predict(np.array([scaled_to_predict_next]))
print("The predicted numbers for the next draw are:\n", scaler.inverse_transform(y_pred_next).astype(int)[0])

1/1 [==============================] - 0s 22ms/step
The predicted numbers for the next draw are:
 [ 9 18 27 31 47  4]
