<a href="https://colab.research.google.com/github/Snowdenstyll/keno/blob/main/Keno_Lottery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [4]:
df = pd.read_csv("/content/2023.csv")

In [5]:
df.head()

PlayDate AP  N01  N02  N03  N04  N05  N06  N07  N08  ...  N11  N12  N13  \
0  2023-01-01  A    3    7    9   14   19   21   22   30  ...   38   39   43   
1  2023-01-01  P    4    5   10   11   13   18   19   27  ...   37   41   43   
2  2023-01-02  A    2    9   11   14   21   24   29   38  ...   47   48   50   
3  2023-01-02  P    2    3    4    7   15   24   25   30  ...   44   47   48   
4  2023-01-03  A    5    6    7   10   21   22   24   25  ...   34   39   43   

   N14  N15  N16  N17  N18  N19  N20  
0   53   54   56   61   64   65   69  
1   44   47   48   55   58   63   70  
2   57   58   59   60   61   66   70  
3   53   54   56   58   60   66   68  
4   45   46   48   49   57   59   65  

[5 rows x 22 columns]

In [6]:
df.tail()

PlayDate AP  N01  N02  N03  N04  N05  N06  N07  N08  ...  N11  N12  \
668  2023-12-02  A    1    2    4    6    9   15   18   20  ...   28   29   
669  2023-12-02  P    2    5    8   12   18   19   23   25  ...   36   38   
670  2023-12-03  A    4    6    7    8   10   14   19   29  ...   40   45   
671  2023-12-03  P    1    5    6    9   11   12   15   22  ...   29   31   
672  2023-12-04  A    7    9   12   14   16   18   20   24  ...   34   44   

     N13  N14  N15  N16  N17  N18  N19  N20  
668   31   33   44   49   57   61   64   65  
669   44   50   51   53   54   55   60   68  
670   55   56   60   61   63   64   65   66  
671   38   39   40   46   51   52   59   69  
672   45   47   49   51   54   59   64   70  

[5 rows x 22 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   PlayDate  673 non-null    object
 1   AP        673 non-null    object
 2   N01       673 non-null    int64 
 3   N02       673 non-null    int64 
 4   N03       673 non-null    int64 
 5   N04       673 non-null    int64 
 6   N05       673 non-null    int64 
 7   N06       673 non-null    int64 
 8   N07       673 non-null    int64 
 9   N08       673 non-null    int64 
 10  N09       673 non-null    int64 
 11  N10       673 non-null    int64 
 12  N11       673 non-null    int64 
 13  N12       673 non-null    int64 
 14  N13       673 non-null    int64 
 15  N14       673 non-null    int64 
 16  N15       673 non-null    int64 
 17  N16       673 non-null    int64 
 18  N17       673 non-null    int64 
 19  N18       673 non-null    int64 
 20  N19       673 non-null    int64 
 21  N20       673 no

In [8]:
df.describe()

N01        N02         N03         N04         N05         N06  \
count  673.000000  673.00000  673.000000  673.000000  673.000000  673.000000   
mean     3.111441    6.41159    9.790490   13.056464   16.638930   20.245171   
std      2.364998    3.36451    4.124451    4.838132    5.388378    5.788760   
min      1.000000    2.00000    3.000000    4.000000    5.000000    8.000000   
25%      1.000000    4.00000    7.000000    9.000000   13.000000   16.000000   
50%      2.000000    6.00000    9.000000   12.000000   16.000000   20.000000   
75%      4.000000    8.00000   12.000000   16.000000   20.000000   24.000000   
max     15.000000   19.00000   27.000000   28.000000   35.000000   43.000000   

              N07         N08         N09         N10         N11         N12  \
count  673.000000  673.000000  673.000000  673.000000  673.000000  673.000000   
mean    23.668648   27.179792   30.600297   33.878158   37.225854   40.475483   
std      5.977526    5.910448    6.002415    5.990569    6.056489    6.120789   
min     11.000000   12.000000   14.000000   17.000000   20.000000   23.000000   
25%     20.000000   23.000000   26.000000   30.000000   33.000000   36.000000   
50%     23.000000   27.000000   31.000000   34.000000   37.000000   40.000000   
75%     27.000000   31.000000   34.000000   37.000000   41.000000   45.000000   
max     46.000000   47.000000   49.000000   51.000000   54.000000   57.000000   

              N13         N14         N15         N16         N17         N18  \
count  673.000000  673.000000  673.000000  673.000000  673.000000  673.000000   
mean    43.903418   47.475483   50.805349   53.971768   57.402675   60.710253   
std      5.939016    5.673645    5.502367    5.243259    4.735233    4.362056   
min     25.000000   31.000000   35.000000   37.000000   39.000000   40.000000   
25%     40.000000   44.000000   47.000000   50.000000   54.000000   58.000000   
50%     44.000000   48.000000   51.000000   55.000000   58.000000   61.000000   
75%     48.000000   52.000000   55.000000   58.000000   61.000000   64.000000   
max     58.000000   61.000000   62.000000   64.000000   67.000000   68.000000   

              N19         N20  
count  673.000000  673.000000  
mean    64.115899   67.664190  
std      3.694623    2.517825  
min     46.000000   58.000000  
25%     62.000000   66.000000  
50%     65.000000   68.000000  
75%     67.000000   70.000000  
max     69.000000   70.000000

In [9]:
df.drop(['PlayDate', 'AP'], axis=1, inplace=True)

In [10]:
df.head()

N01  N02  N03  N04  N05  N06  N07  N08  N09  N10  N11  N12  N13  N14  N15  \
0    3    7    9   14   19   21   22   30   32   34   38   39   43   53   54   
1    4    5   10   11   13   18   19   27   31   32   37   41   43   44   47   
2    2    9   11   14   21   24   29   38   40   42   47   48   50   57   58   
3    2    3    4    7   15   24   25   30   38   39   44   47   48   53   54   
4    5    6    7   10   21   22   24   25   26   32   34   39   43   45   46   

   N16  N17  N18  N19  N20  
0   56   61   64   65   69  
1   48   55   58   63   70  
2   59   60   61   66   70  
3   56   58   60   66   68  
4   48   49   57   59   65

In [11]:
scaler = StandardScaler().fit(df.values)
transformed_dataset = scaler.transform(df.values)
transformed_df = pd.DataFrame(data=transformed_dataset, index=df.index)

In [12]:
transformed_df.head()

0         1         2         3         4         5         6   \
0 -0.047156  0.175017 -0.191802  0.195166  0.438504  0.130493 -0.279361   
1  0.375992 -0.419865  0.050835 -0.425369 -0.675832 -0.388139 -0.781614   
2 -0.470304  0.769900  0.293472  0.195166  0.809949  0.649124  0.892563   
3 -0.470304 -1.014747 -1.404986 -1.252750 -0.304386  0.649124  0.222892   
4  0.799139 -0.122424 -0.677076 -0.632214  0.809949  0.303370  0.055474   

         7         8         9         10        11        12        13  \
0  0.477511  0.233363  0.020354  0.127916 -0.241240 -0.152229  0.974440   
1 -0.030442  0.066640 -0.313752 -0.037319  0.085758 -0.152229 -0.613022   
2  1.832053  1.567152  1.356780  1.615031  1.230252  1.027294  1.679978   
3  0.477511  1.233704  0.855620  1.119326  1.066753  0.690288  0.974440   
4 -0.369077 -0.766978 -0.313752 -0.533024 -0.241240 -0.152229 -0.436637   

         14        15        16        17        18        19  
0  0.581028  0.387114  0.760258  0.754735  0.239472  0.530936  
1 -0.692098 -1.139789 -0.507781 -0.621787 -0.302258  0.928399  
2  1.308528  0.959703  0.548919  0.066474  0.510337  0.928399  
3  0.581028  0.387114  0.126239 -0.162946  0.510337  0.133472  
4 -0.873974 -1.139789 -1.775821 -0.851207 -1.385718 -1.058918

In [13]:
# All our games
number_of_rows = df.values.shape[0]
number_of_rows

673

In [14]:
# Amount of games we need to take into consideration for prediction
window_length = 4
window_length

4

In [15]:
# Balls counts
number_of_features = df.values.shape[1]
number_of_features

20

In [16]:
X = np.empty([ number_of_rows - window_length, window_length, number_of_features], dtype=float)
X

array([[[0.00000000e+000, 4.92750342e-310, 5.70645821e-320, ...,
         1.79739669e-052, 2.42136937e-052, 8.54295461e-072],
        [6.96324158e-077, 1.65662340e-153, 1.83255449e-076, ...,
         4.27855901e-033, 5.59867395e-067, 6.96324176e-077],
        [1.65662340e-153, 4.01831818e-057, 3.89262071e-033, ...,
         1.03277984e-047, 1.25767777e-076, 1.50600100e-153],
        [4.01831818e-057, 3.93798326e-062, 1.30354286e-076, ...,
         3.37734755e-057, 4.46739922e-033, 2.89630842e-057]],

       [[3.25266773e-086, 6.04999052e-154, 1.74484474e-076, ...,
         1.83019696e-076, 4.41941945e-062, 3.44353330e-086],
        [6.04274682e-154, 6.82478187e-038, 6.04159263e-154, ...,
         2.89630842e-057, 3.25266773e-086, 2.48882174e-091],
        [8.61485316e-043, 1.81154498e-152, 6.01347002e-154, ...,
         5.86043777e+135, 4.27179401e-033, 3.45374429e-086],
        [2.48883584e-091, 1.37055925e-071, 7.71101552e-043, ...,
         8.23297732e-067, 1.17553222e-047, 3.242456

In [17]:
y = np.empty([ number_of_rows - window_length, number_of_features], dtype=float)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
for i in range(0, number_of_rows-window_length):
    X[i] = transformed_df.iloc[i : i+window_length, 0 : number_of_features]
    y[i] = transformed_df.iloc[i+window_length : i+window_length+1, 0 : number_of_features]

In [19]:
X.shape

(669, 4, 20)

In [20]:
y.shape

(669, 20)

In [21]:
X[0]

array([[-0.04715614,  0.17501741, -0.19180206,  0.19516586,  0.43850415,
         0.13049263, -0.27936122,  0.47751125,  0.23336338,  0.02035418,
         0.12791593, -0.2412402 , -0.15222884,  0.97443992,  0.58102756,
         0.38711429,  0.76025844,  0.75473459,  0.23947197,  0.53093567],
       [ 0.37599163, -0.41986499,  0.05083476, -0.42536936, -0.67583176,
        -0.38813853, -0.78161439, -0.03044197,  0.06663986, -0.31375223,
        -0.03731904,  0.0857581 , -0.15222884, -0.61302178, -0.69209842,
        -1.13978925, -0.50778104, -0.62178676, -0.3022579 ,  0.9283992 ],
       [-0.47030391,  0.7698998 ,  0.29347157,  0.19516586,  0.80994945,
         0.6491238 ,  0.89256283,  1.83205317,  1.56715152,  1.35677983,
         1.6150307 ,  1.23025215,  1.02729429,  1.67997845,  1.30852812,
         0.95970311,  0.54891853,  0.06647391,  0.5103369 ,  0.9283992 ],
       [-0.47030391, -1.01474738, -1.40498614, -1.25274966, -0.30438645,
         0.6491238 ,  0.22289194,  0.47751125,  

In [22]:
X[1]

array([[ 0.37599163, -0.41986499,  0.05083476, -0.42536936, -0.67583176,
        -0.38813853, -0.78161439, -0.03044197,  0.06663986, -0.31375223,
        -0.03731904,  0.0857581 , -0.15222884, -0.61302178, -0.69209842,
        -1.13978925, -0.50778104, -0.62178676, -0.3022579 ,  0.9283992 ],
       [-0.47030391,  0.7698998 ,  0.29347157,  0.19516586,  0.80994945,
         0.6491238 ,  0.89256283,  1.83205317,  1.56715152,  1.35677983,
         1.6150307 ,  1.23025215,  1.02729429,  1.67997845,  1.30852812,
         0.95970311,  0.54891853,  0.06647391,  0.5103369 ,  0.9283992 ],
       [-0.47030391, -1.01474738, -1.40498614, -1.25274966, -0.30438645,
         0.6491238 ,  0.22289194,  0.47751125,  1.23370448,  0.85562021,
         1.11932577,  1.066753  ,  0.69028768,  0.97443992,  0.58102756,
         0.38711429,  0.1262387 , -0.16294631,  0.5103369 ,  0.13347215],
       [ 0.7991394 , -0.12242379, -0.67707569, -0.63221444,  0.80994945,
         0.30336969,  0.05547422, -0.36907745, -

In [23]:
y[0]

array([ 0.7991394 , -0.12242379, -0.67707569, -0.63221444,  0.80994945,
        0.30336969,  0.05547422, -0.36907745, -0.76697773, -0.31375223,
       -0.53302396, -0.2412402 , -0.15222884, -0.43663715, -0.87397356,
       -1.13978925, -1.77582052, -0.85120699, -1.38571763, -1.05891842])

In [24]:
y[1]

array([-0.89345168,  1.067341  ,  1.26401884,  0.81570108,  1.7385627 ,
        2.37789433,  2.2319046 ,  2.17068865,  1.90059855,  1.69088624,
        1.6150307 ,  1.3937513 ,  1.19579759,  0.79805529,  1.6722784 ,
        1.53229194,  1.18293827,  1.44299527,  1.05206677,  0.53093567])

In [25]:
# Recurrent Neural Netowrk (RNN) with Long Short Term Memory (LSTM)
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, Dropout
batch_size = 100

In [26]:
# Initialising the RNN
model = Sequential()
# Adding the input layer and the LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a first Dropout layer
model.add(Dropout(0.2))
# Adding a second LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a second Dropout layer
model.add(Dropout(0.2))
# Adding a third LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a fourth LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = False)))
# Adding a fourth Dropout layer
model.add(Dropout(0.2))
# Adding the first output layer
model.add(Dense(70))
# Adding the last output layer
model.add(Dense(number_of_features))

In [27]:
from tensorflow import keras
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.0001), loss ='mse', metrics=['accuracy'])

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9, random_state=90)

# Train the model
#history = model.fit(X_train, y_train, batch_size=100, epochs=400, verbose=2)
history = model.fit(X_train, y_train, batch_size=100, epochs=600, verbose=2)


Epoch 1/600
1/1 - 23s - loss: 1.0101 - accuracy: 0.0000e+00 - 23s/epoch - 23s/step
Epoch 2/600
1/1 - 0s - loss: 1.0089 - accuracy: 0.0303 - 22ms/epoch - 22ms/step
Epoch 3/600
1/1 - 0s - loss: 1.0077 - accuracy: 0.0909 - 22ms/epoch - 22ms/step
Epoch 4/600
1/1 - 0s - loss: 1.0062 - accuracy: 0.0758 - 22ms/epoch - 22ms/step
Epoch 5/600
1/1 - 0s - loss: 1.0048 - accuracy: 0.1212 - 26ms/epoch - 26ms/step
Epoch 6/600
1/1 - 0s - loss: 1.0038 - accuracy: 0.0909 - 22ms/epoch - 22ms/step
Epoch 7/600
1/1 - 0s - loss: 1.0022 - accuracy: 0.1667 - 22ms/epoch - 22ms/step
Epoch 8/600
1/1 - 0s - loss: 1.0006 - accuracy: 0.1212 - 23ms/epoch - 23ms/step
Epoch 9/600
1/1 - 0s - loss: 0.9998 - accuracy: 0.1364 - 20ms/epoch - 20ms/step
Epoch 10/600
1/1 - 0s - loss: 0.9983 - accuracy: 0.1515 - 19ms/epoch - 19ms/step
Epoch 11/600
1/1 - 0s - loss: 0.9963 - accuracy: 0.1061 - 22ms/epoch - 22ms/step
Epoch 12/600
1/1 - 0s - loss: 0.9947 - accuracy: 0.1667 - 20ms/epoch - 20ms/step
Epoch 13/600
1/1 - 0s - loss: 0.99

In [98]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=2)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

19/19 - 0s - loss: 1.7523 - accuracy: 0.0597 - 167ms/epoch - 9ms/step
Test Loss: 1.7523460388183594, Test Accuracy: 0.05970149114727974


In [30]:
#history = model.fit(X_train, y_train, batch_size=50, epochs=100, verbose=2)
history = model.fit(X_train, y_train, batch_size=50, epochs=100, verbose=2)

Epoch 1/100
2/2 - 0s - loss: 0.0733 - accuracy: 0.5606 - 39ms/epoch - 20ms/step
Epoch 2/100
2/2 - 0s - loss: 0.0774 - accuracy: 0.5455 - 31ms/epoch - 15ms/step
Epoch 3/100
2/2 - 0s - loss: 0.0762 - accuracy: 0.6061 - 31ms/epoch - 16ms/step
Epoch 4/100
2/2 - 0s - loss: 0.0801 - accuracy: 0.6061 - 33ms/epoch - 17ms/step
Epoch 5/100
2/2 - 0s - loss: 0.0792 - accuracy: 0.6061 - 34ms/epoch - 17ms/step
Epoch 6/100
2/2 - 0s - loss: 0.0785 - accuracy: 0.5303 - 33ms/epoch - 16ms/step
Epoch 7/100
2/2 - 0s - loss: 0.0715 - accuracy: 0.5303 - 34ms/epoch - 17ms/step
Epoch 8/100
2/2 - 0s - loss: 0.0733 - accuracy: 0.6212 - 33ms/epoch - 17ms/step
Epoch 9/100
2/2 - 0s - loss: 0.0753 - accuracy: 0.5455 - 30ms/epoch - 15ms/step
Epoch 10/100
2/2 - 0s - loss: 0.0787 - accuracy: 0.6061 - 32ms/epoch - 16ms/step
Epoch 11/100
2/2 - 0s - loss: 0.0770 - accuracy: 0.5000 - 31ms/epoch - 15ms/step
Epoch 12/100
2/2 - 0s - loss: 0.0742 - accuracy: 0.6061 - 41ms/epoch - 21ms/step
Epoch 13/100
2/2 - 0s - loss: 0.0854 

In [90]:
df1 = df.copy()
to_predict = df.tail(3)
to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)
to_predict

<ipython-input-90-a91c54494079>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)


N01  N02  N03  N04  N05  N06  N07  N08  N09  N10  N11  N12  N13  N14  \
670    4    6    7    8   10   14   19   29   30   33   40   45   55   56   
671    1    5    6    9   11   12   15   22   23   27   29   31   38   39   

     N15  N16  N17  N18  N19  N20  
670   60   61   63   64   65   66  
671   40   46   51   52   59   69

In [99]:
to_predict = np.array(to_predict)
to_predict

array([[ 4,  6,  7,  8, 10, 14, 19, 29, 30, 33, 40, 45, 55, 56, 60, 61,
        63, 64, 65, 66],
       [ 1,  5,  6,  9, 11, 12, 15, 22, 23, 27, 29, 31, 38, 39, 40, 46,
        51, 52, 59, 69]])

In [92]:
scaled_to_predict = scaler.transform(to_predict)

In [93]:
y_pred = model.predict(np.array([scaled_to_predict]))
print("The predicted numbers in the last lottery game are:", scaler.inverse_transform(y_pred).astype(int)[0])

1/1 [==============================] - 0s 20ms/step
The predicted numbers in the last lottery game are: [ 2  5  9 12 16 21 25 28 32 35 38 41 45 48 51 54 57 60 64 67]


In [94]:
prediction = df.tail(1)
prediction = np.array(prediction)
print("The actual numbers in the last lottery game were:", prediction[0])

The actual numbers in the last lottery game were: [ 7  9 12 14 16 18 20 24 25 30 34 44 45 47 49 51 54 59 64 70]


In [95]:
temp = np.array(scaler.inverse_transform(y_pred).astype(int)[0])
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("winners:", duplicates)
print(len(duplicates)/20)

winners: [ 9 12 16 25 45 51 54 64]
0.4


# Predict the next set of numbers

In [37]:
next = df.copy()
next = next.tail((window_length))
next

N01  N02  N03  N04  N05  N06  N07  N08  N09  N10  N11  N12  N13  N14  \
669    2    5    8   12   18   19   23   25   28   34   36   38   44   50   
670    4    6    7    8   10   14   19   29   30   33   40   45   55   56   
671    1    5    6    9   11   12   15   22   23   27   29   31   38   39   
672    7    9   12   14   16   18   20   24   25   30   34   44   45   47   

     N15  N16  N17  N18  N19  N20  
669   51   53   54   55   60   68  
670   60   61   63   64   65   66  
671   40   46   51   52   59   69  
672   49   51   54   59   64   70

In [75]:
next = np.array(next)
next

array([[ 2,  5,  8, 12, 18, 19, 23, 25, 28, 34, 36, 38, 44, 50, 51, 53,
        54, 55, 60, 68],
       [ 4,  6,  7,  8, 10, 14, 19, 29, 30, 33, 40, 45, 55, 56, 60, 61,
        63, 64, 65, 66],
       [ 1,  5,  6,  9, 11, 12, 15, 22, 23, 27, 29, 31, 38, 39, 40, 46,
        51, 52, 59, 69],
       [ 7,  9, 12, 14, 16, 18, 20, 24, 25, 30, 34, 44, 45, 47, 49, 51,
        54, 59, 64, 70]])

In [74]:
x_next = scaler.transform(next)
x_next

next_Date = '2023-12-01 Evening';

In [80]:
y_next_pred = model.predict(np.array([x_next]))
print("The predicted numbers for the lottery game which will take place on",next_Date, "are (without rounding up):\n", scaler.inverse_transform(y_next_pred).astype(int)[0])

print("\n")
temp = np.array(scaler.inverse_transform(y_next_pred).astype(int)[0])
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("without rounding up")
print("winners:", duplicates)
print(len(duplicates)/20)

1/1 [==============================] - 0s 24ms/step
The predicted numbers for the lottery game which will take place on 2023-12-01 Evening are (without rounding up):
 [ 2  3  4  7 11 18 23 26 30 36 38 40 45 49 53 55 56 60 63 67]


without rounding up
winners: [ 7 18 30 45 49]
0.25


In [72]:
y_next_pred = model.predict(np.array([x_next]))
print("The predicted numbers for the lottery game which will take place on",next_Date, "are (with rounding up):\n", scaler.inverse_transform(y_next_pred).astype(int)[0]+1)

1/1 [==============================] - 0s 22ms/step
The predicted numbers for the lottery game which will take place on 2023-12-01 Evening are (with rounding up):
 [ 3  4  5  8 12 19 24 27 31 37 39 41 46 50 54 56 57 61 64 68]


In [73]:
temp = np.array(scaler.inverse_transform(y_next_pred).astype(int)[0]+1)
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("with rounding up")
print("winners:", duplicates)
print(len(duplicates)/20)

with rounding up
winners: [12 24 54 64]
0.2


In [96]:
to_predict_next = df.tail(3)
to_predict_next = np.array(to_predict_next)
to_predict_next

array([[ 4,  6,  7,  8, 10, 14, 19, 29, 30, 33, 40, 45, 55, 56, 60, 61,
        63, 64, 65, 66],
       [ 1,  5,  6,  9, 11, 12, 15, 22, 23, 27, 29, 31, 38, 39, 40, 46,
        51, 52, 59, 69],
       [ 7,  9, 12, 14, 16, 18, 20, 24, 25, 30, 34, 44, 45, 47, 49, 51,
        54, 59, 64, 70]])

In [97]:
scaled_to_predict_next = scaler.transform(to_predict_next)
y_pred_next = model.predict(np.array([scaled_to_predict_next]))
print("The predicted numbers for the next draw are:\n", scaler.inverse_transform(y_pred_next).astype(int)[0])

1/1 [==============================] - 0s 33ms/step
The predicted numbers for the next draw are:
 [ 3  5  7 10 15 19 24 27 31 34 37 39 43 47 50 53 56 60 63 67]
