<a href="https://colab.research.google.com/github/Snowdenstyll/keno/blob/main/Keno_Lottery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [9]:
df = pd.read_csv("/content/2023.csv")

In [10]:
df.head()

PlayDate AP  N01  N02  N03  N04  N05  N06  N07  N08  ...  N11  N12  N13  \
0  2023-01-01  A    3    7    9   14   19   21   22   30  ...   38   39   43   
1  2023-01-01  P    4    5   10   11   13   18   19   27  ...   37   41   43   
2  2023-01-02  A    2    9   11   14   21   24   29   38  ...   47   48   50   
3  2023-01-02  P    2    3    4    7   15   24   25   30  ...   44   47   48   
4  2023-01-03  A    5    6    7   10   21   22   24   25  ...   34   39   43   

   N14  N15  N16  N17  N18  N19  N20  
0   53   54   56   61   64   65   69  
1   44   47   48   55   58   63   70  
2   57   58   59   60   61   66   70  
3   53   54   56   58   60   66   68  
4   45   46   48   49   57   59   65  

[5 rows x 22 columns]

In [11]:
df.tail()

PlayDate AP  N01  N02  N03  N04  N05  N06  N07  N08  ...  N11  N12  \
670  2023-12-03  A    4    6    7    8   10   14   19   29  ...   40   45   
671  2023-12-03  P    1    5    6    9   11   12   15   22  ...   29   31   
672  2023-12-04  A    7    9   12   14   16   18   20   24  ...   34   44   
673  2023-12-04  P    1    3    6    7   16   20   31   35  ...   49   50   
674  2023-12-05  A    6    7    8   18   20   21   24   25  ...   37   39   

     N13  N14  N15  N16  N17  N18  N19  N20  
670   55   56   60   61   63   64   65   66  
671   38   39   40   46   51   52   59   69  
672   45   47   49   51   54   59   64   70  
673   51   52   53   55   56   57   63   64  
674   44   50   55   56   58   60   61   66  

[5 rows x 22 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 675 entries, 0 to 674
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   PlayDate  675 non-null    object
 1   AP        675 non-null    object
 2   N01       675 non-null    int64 
 3   N02       675 non-null    int64 
 4   N03       675 non-null    int64 
 5   N04       675 non-null    int64 
 6   N05       675 non-null    int64 
 7   N06       675 non-null    int64 
 8   N07       675 non-null    int64 
 9   N08       675 non-null    int64 
 10  N09       675 non-null    int64 
 11  N10       675 non-null    int64 
 12  N11       675 non-null    int64 
 13  N12       675 non-null    int64 
 14  N13       675 non-null    int64 
 15  N14       675 non-null    int64 
 16  N15       675 non-null    int64 
 17  N16       675 non-null    int64 
 18  N17       675 non-null    int64 
 19  N18       675 non-null    int64 
 20  N19       675 non-null    int64 
 21  N20       675 no

In [13]:
df.describe()

N01         N02         N03         N04         N05         N06  \
count  675.000000  675.000000  675.000000  675.000000  675.000000  675.000000   
mean     3.112593    6.407407    9.782222   13.054815   16.642963   20.245926   
std      2.365505    3.362157    4.121484    4.840325    5.381989    5.780246   
min      1.000000    2.000000    3.000000    4.000000    5.000000    8.000000   
25%      1.000000    4.000000    7.000000    9.000000   13.000000   16.000000   
50%      2.000000    6.000000    9.000000   12.000000   16.000000   20.000000   
75%      4.000000    8.000000   12.000000   16.000000   20.000000   24.000000   
max     15.000000   19.000000   27.000000   28.000000   35.000000   43.000000   

             N07         N08         N09         N10         N11         N12  \
count  675.00000  675.000000  675.000000  675.000000  675.000000  675.000000   
mean    23.68000   27.188148   30.613333   33.893333   37.242963   40.487407   
std      5.97533    5.909945    6.000504    5.990388    6.064460    6.122954   
min     11.00000   12.000000   14.000000   17.000000   20.000000   23.000000   
25%     20.00000   23.000000   26.000000   30.000000   33.000000   36.000000   
50%     23.00000   27.000000   31.000000   34.000000   37.000000   40.000000   
75%     27.50000   31.000000   34.500000   37.000000   41.000000   45.000000   
max     46.00000   47.000000   49.000000   51.000000   54.000000   57.000000   

              N13         N14         N15         N16         N17         N18  \
count  675.000000  675.000000  675.000000  675.000000  675.000000  675.000000   
mean    43.914074   47.485926   50.814815   53.976296   57.401481   60.703704   
std      5.936486    5.668725    5.497214    5.236204    4.728567    4.358004   
min     25.000000   31.000000   35.000000   37.000000   39.000000   40.000000   
25%     40.000000   44.000000   47.000000   50.000000   54.000000   58.000000   
50%     44.000000   48.000000   51.000000   55.000000   58.000000   61.000000   
75%     48.000000   52.000000   55.000000   58.000000   61.000000   64.000000   
max     58.000000   61.000000   62.000000   64.000000   67.000000   68.000000   

              N19         N20  
count  675.000000  675.000000  
mean    64.109630   67.656296  
std      3.691334    2.518849  
min     46.000000   58.000000  
25%     62.000000   66.000000  
50%     65.000000   68.000000  
75%     67.000000   70.000000  
max     69.000000   70.000000

In [14]:
df.drop(['PlayDate', 'AP'], axis=1, inplace=True)

In [15]:
df.head()

N01  N02  N03  N04  N05  N06  N07  N08  N09  N10  N11  N12  N13  N14  N15  \
0    3    7    9   14   19   21   22   30   32   34   38   39   43   53   54   
1    4    5   10   11   13   18   19   27   31   32   37   41   43   44   47   
2    2    9   11   14   21   24   29   38   40   42   47   48   50   57   58   
3    2    3    4    7   15   24   25   30   38   39   44   47   48   53   54   
4    5    6    7   10   21   22   24   25   26   32   34   39   43   45   46   

   N16  N17  N18  N19  N20  
0   56   61   64   65   69  
1   48   55   58   63   70  
2   59   60   61   66   70  
3   56   58   60   66   68  
4   48   49   57   59   65

In [16]:
scaler = StandardScaler().fit(df.values)
transformed_dataset = scaler.transform(df.values)
transformed_df = pd.DataFrame(data=transformed_dataset, index=df.index)

In [17]:
transformed_df.head()

0         1         2         3         4         5         6   \
0 -0.047633  0.176384 -0.189932  0.195418  0.438274  0.130554 -0.281365   
1  0.375423 -0.418913  0.052879 -0.424835 -0.677382 -0.388840 -0.783801   
2 -0.470689  0.771682  0.295690  0.195418  0.810159  0.649948  0.890988   
3 -0.470689 -1.014210 -1.403987 -1.251839 -0.305497  0.649948  0.221072   
4  0.798479 -0.121264 -0.675554 -0.631586  0.810159  0.303685  0.053593   

         7         8         9         10        11        12        13  \
0  0.476136  0.231263  0.017820  0.124924 -0.243103 -0.154090  0.973440   
1 -0.031859  0.064487 -0.316296 -0.040093  0.083779 -0.154090 -0.615396   
2  1.830790  1.565473  1.354283  1.610081  1.227865  1.025933  1.679589   
3  0.476136  1.231920  0.853109  1.115029  1.064424  0.688784  0.973440   
4 -0.370523 -0.769394 -0.316296 -0.535145 -0.243103 -0.154090 -0.438859   

         14        15        16        17        18        19  
0  0.579848  0.386770  0.761581  0.756938  0.241384  0.533855  
1 -0.694469 -1.142188 -0.508243 -0.620860 -0.300827  0.931156  
2  1.308029  0.960129  0.549944  0.068039  0.512490  0.931156  
3  0.579848  0.386770  0.126669 -0.161594  0.512490  0.136554  
4 -0.876514 -1.142188 -1.778068 -0.850493 -1.385250 -1.055350

In [18]:
# All our games
number_of_rows = df.values.shape[0]
number_of_rows

675

In [19]:
# Amount of games we need to take into consideration for prediction
window_length = 4
window_length

4

In [20]:
# Balls counts
number_of_features = df.values.shape[1]
number_of_features

20

In [21]:
X = np.empty([ number_of_rows - window_length, window_length, number_of_features], dtype=float)
X

array([[[1.26770919e-002, 7.87491907e-001, 1.23786228e+000, ...,
         3.56230672e+000, 1.26770919e-002, 8.33712154e+000],
        [1.26770919e-002, 4.46304746e+000, 4.46304746e+000, ...,
         4.46304746e+000, 4.46304746e+000, 1.23786228e+000],
        [1.26770919e-002, 1.26770919e-002, 4.46304746e+000, ...,
         1.23786228e+000, 4.46304746e+000, 4.46304746e+000],
        [1.26770919e-002, 4.46304746e+000, 1.23786228e+000, ...,
         3.56230672e+000, 3.56230672e+000, 4.46304746e+000]],

       [[8.33712154e+000, 3.46615660e+001, 4.46304746e+000, ...,
         1.26770919e-002, 7.87491907e-001, 4.46304746e+000],
        [1.23786228e+000, 1.51119364e+001, 4.46304746e+000, ...,
         4.46304746e+000, 1.23786228e+000, 1.23786228e+000],
        [1.26770919e-002, 1.23786228e+000, 3.56230672e+000, ...,
         1.51119364e+001, 3.56230672e+000, 8.33712154e+000],
        [1.26770919e-002, 8.33712154e+000, 3.56230672e+000, ...,
         4.46304746e+000, 4.46304746e+000, 1.237862

In [22]:
y = np.empty([ number_of_rows - window_length, number_of_features], dtype=float)
y

array([[7.1659e-320, 7.1674e-320, 7.1689e-320, ..., 7.1926e-320,
        7.1941e-320, 7.1956e-320],
       [7.1971e-320, 7.1985e-320, 7.2000e-320, ..., 7.2247e-320,
        7.2262e-320, 7.2277e-320],
       [7.2292e-320, 7.2307e-320, 7.2321e-320, ..., 7.2558e-320,
        7.2573e-320, 7.2588e-320],
       ...,
       [0.0000e+000, 0.0000e+000, 0.0000e+000, ..., 0.0000e+000,
        0.0000e+000, 0.0000e+000],
       [0.0000e+000, 0.0000e+000, 0.0000e+000, ..., 0.0000e+000,
        0.0000e+000, 0.0000e+000],
       [0.0000e+000, 0.0000e+000, 0.0000e+000, ..., 0.0000e+000,
        0.0000e+000, 0.0000e+000]])

In [23]:
for i in range(0, number_of_rows-window_length):
    X[i] = transformed_df.iloc[i : i+window_length, 0 : number_of_features]
    y[i] = transformed_df.iloc[i+window_length : i+window_length+1, 0 : number_of_features]

In [24]:
X.shape

(671, 4, 20)

In [25]:
y.shape

(671, 20)

In [26]:
X[0]

array([[-0.047633  ,  0.1763844 , -0.18993216,  0.19541791,  0.43827382,
         0.13055384, -0.28136451,  0.47613587,  0.23126305,  0.01781951,
         0.1249243 , -0.24310331, -0.1540898 ,  0.97343987,  0.57984773,
         0.38676956,  0.76158107,  0.75693847,  0.24138446,  0.533855  ],
       [ 0.37542325, -0.41891295,  0.05287884, -0.42483486, -0.67738235,
        -0.38884012, -0.78380114, -0.03185946,  0.06448681, -0.31629627,
        -0.04009312,  0.08377863, -0.1540898 , -0.61539603, -0.69446879,
        -1.1421877 , -0.50824328, -0.62085964, -0.30082689,  0.93115612],
       [-0.47068925,  0.77168175,  0.29568984,  0.19541791,  0.81015921,
         0.64994779,  0.89098762,  1.83079007,  1.56547297,  1.35428262,
         1.61008108,  1.22786541,  1.02593339,  1.67958915,  1.3080286 ,
         0.96012853,  0.54994368,  0.06803941,  0.51249014,  0.93115612],
       [-0.47068925, -1.0142103 , -1.40398717, -1.25183855, -0.30549696,
         0.64994779,  0.22107212,  0.47613587,  

In [27]:
X[1]

array([[ 0.37542325, -0.41891295,  0.05287884, -0.42483486, -0.67738235,
        -0.38884012, -0.78380114, -0.03185946,  0.06448681, -0.31629627,
        -0.04009312,  0.08377863, -0.1540898 , -0.61539603, -0.69446879,
        -1.1421877 , -0.50824328, -0.62085964, -0.30082689,  0.93115612],
       [-0.47068925,  0.77168175,  0.29568984,  0.19541791,  0.81015921,
         0.64994779,  0.89098762,  1.83079007,  1.56547297,  1.35428262,
         1.61008108,  1.22786541,  1.02593339,  1.67958915,  1.3080286 ,
         0.96012853,  0.54994368,  0.06803941,  0.51249014,  0.93115612],
       [-0.47068925, -1.0142103 , -1.40398717, -1.25183855, -0.30549696,
         0.64994779,  0.22107212,  0.47613587,  1.23192049,  0.85310895,
         1.11502882,  1.06442444,  0.68878391,  0.97343987,  0.57984773,
         0.38676956,  0.1266689 , -0.16159361,  0.51249014,  0.13655387],
       [ 0.7984795 , -0.12126428, -0.67555417, -0.63158578,  0.81015921,
         0.30368516,  0.05359324, -0.37052301, -

In [28]:
y[0]

array([ 0.7984795 , -0.12126428, -0.67555417, -0.63158578,  0.81015921,
        0.30368516,  0.05359324, -0.37052301, -0.76939439, -0.31629627,
       -0.53514538, -0.24310331, -0.1540898 , -0.4388587 , -0.87651401,
       -1.1421877 , -1.77806762, -0.85049266, -1.3852496 , -1.05534951])

In [29]:
y[1]

array([-0.8937455 ,  1.06933043,  1.26693385,  0.81567068,  1.73987268,
        2.38126098,  2.23081862,  2.16945362,  1.89902545,  1.6883984 ,
        1.61008108,  1.39130638,  1.19450813,  0.79690255,  1.67211903,
        1.53348751,  1.18485585,  1.44583753,  1.05470149,  0.533855  ])

In [30]:
# Recurrent Neural Netowrk (RNN) with Long Short Term Memory (LSTM)
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, Dropout
batch_size = 100

In [31]:
# Initialising the RNN
model = Sequential()
# Adding the input layer and the LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a first Dropout layer
model.add(Dropout(0.2))
# Adding a second LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a second Dropout layer
model.add(Dropout(0.2))
# Adding a third LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a fourth LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = False)))
# Adding a fourth Dropout layer
model.add(Dropout(0.2))
# Adding the first output layer
model.add(Dense(70))
# Adding the last output layer
model.add(Dense(number_of_features))

In [32]:
from tensorflow import keras
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.0001), loss ='mse', metrics=['accuracy'])

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9, random_state=90)

# Train the model
history = model.fit(X, y, batch_size=100, epochs=1000, verbose=2)
#history = model.fit(X_train, y_train, batch_size=100, epochs=600, verbose=2)


Epoch 1/1000
7/7 - 0s - loss: 0.0555 - accuracy: 0.6602 - 147ms/epoch - 21ms/step
Epoch 2/1000
7/7 - 0s - loss: 0.0562 - accuracy: 0.6349 - 142ms/epoch - 20ms/step
Epoch 3/1000
7/7 - 0s - loss: 0.0551 - accuracy: 0.6200 - 139ms/epoch - 20ms/step
Epoch 4/1000
7/7 - 0s - loss: 0.0552 - accuracy: 0.6304 - 150ms/epoch - 21ms/step
Epoch 5/1000
7/7 - 0s - loss: 0.0550 - accuracy: 0.6721 - 130ms/epoch - 19ms/step
Epoch 6/1000
7/7 - 0s - loss: 0.0574 - accuracy: 0.6364 - 128ms/epoch - 18ms/step
Epoch 7/1000
7/7 - 0s - loss: 0.0545 - accuracy: 0.6557 - 131ms/epoch - 19ms/step
Epoch 8/1000
7/7 - 0s - loss: 0.0548 - accuracy: 0.6587 - 135ms/epoch - 19ms/step
Epoch 9/1000
7/7 - 0s - loss: 0.0551 - accuracy: 0.6617 - 122ms/epoch - 17ms/step
Epoch 10/1000
7/7 - 0s - loss: 0.0531 - accuracy: 0.6334 - 125ms/epoch - 18ms/step
Epoch 11/1000
7/7 - 0s - loss: 0.0546 - accuracy: 0.6319 - 123ms/epoch - 18ms/step
Epoch 12/1000
7/7 - 0s - loss: 0.0540 - accuracy: 0.6513 - 146ms/epoch - 21ms/step
Epoch 13/1000

In [52]:
loss, accuracy = model.evaluate(X, y, verbose=2)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

21/21 - 0s - loss: 0.0021 - accuracy: 0.9359 - 134ms/epoch - 6ms/step
Test Loss: 0.0021018257830291986, Test Accuracy: 0.935916543006897


In [53]:
#history = model.fit(X_train, y_train, batch_size=50, epochs=100, verbose=2)
#history = model.fit(X_train, y_train, batch_size=50, epochs=100, verbose=2)

In [61]:
df1 = df.copy()
to_predict = df.tail(4)
to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)
to_predict

<ipython-input-61-4c852ff86c2e>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)


N01  N02  N03  N04  N05  N06  N07  N08  N09  N10  N11  N12  N13  N14  \
671    1    5    6    9   11   12   15   22   23   27   29   31   38   39   
672    7    9   12   14   16   18   20   24   25   30   34   44   45   47   
673    1    3    6    7   16   20   31   35   38   42   49   50   51   52   

     N15  N16  N17  N18  N19  N20  
671   40   46   51   52   59   69  
672   49   51   54   59   64   70  
673   53   55   56   57   63   64

In [62]:
to_predict = np.array(to_predict)
to_predict

array([[ 1,  5,  6,  9, 11, 12, 15, 22, 23, 27, 29, 31, 38, 39, 40, 46,
        51, 52, 59, 69],
       [ 7,  9, 12, 14, 16, 18, 20, 24, 25, 30, 34, 44, 45, 47, 49, 51,
        54, 59, 64, 70],
       [ 1,  3,  6,  7, 16, 20, 31, 35, 38, 42, 49, 50, 51, 52, 53, 55,
        56, 57, 63, 64]])

In [63]:
scaled_to_predict = scaler.transform(to_predict)

In [64]:
y_pred = model.predict(np.array([scaled_to_predict]))
print("The predicted numbers in the last lottery game are:", scaler.inverse_transform(y_pred).astype(int)[0])

1/1 [==============================] - 0s 20ms/step
The predicted numbers in the last lottery game are: [ 3  5  7 12 15 17 20 24 27 32 35 38 40 47 50 52 57 60 63 67]


In [65]:
prediction = df.tail(1)
prediction = np.array(prediction)
print("The actual numbers in the last lottery game were:", prediction[0])

The actual numbers in the last lottery game were: [ 6  7  8 18 20 21 24 25 32 36 37 39 44 50 55 56 58 60 61 66]


In [66]:
temp = np.array(scaler.inverse_transform(y_pred).astype(int)[0])
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("winners:", duplicates)
print(len(duplicates)/20)

winners: [ 7 20 24 32 50 60]
0.3


# Predict the next set of numbers

In [67]:
next = df.copy()
next = next.tail((window_length))
next

N01  N02  N03  N04  N05  N06  N07  N08  N09  N10  N11  N12  N13  N14  \
671    1    5    6    9   11   12   15   22   23   27   29   31   38   39   
672    7    9   12   14   16   18   20   24   25   30   34   44   45   47   
673    1    3    6    7   16   20   31   35   38   42   49   50   51   52   
674    6    7    8   18   20   21   24   25   32   36   37   39   44   50   

     N15  N16  N17  N18  N19  N20  
671   40   46   51   52   59   69  
672   49   51   54   59   64   70  
673   53   55   56   57   63   64  
674   55   56   58   60   61   66

In [68]:
next = np.array(next)
next

array([[ 1,  5,  6,  9, 11, 12, 15, 22, 23, 27, 29, 31, 38, 39, 40, 46,
        51, 52, 59, 69],
       [ 7,  9, 12, 14, 16, 18, 20, 24, 25, 30, 34, 44, 45, 47, 49, 51,
        54, 59, 64, 70],
       [ 1,  3,  6,  7, 16, 20, 31, 35, 38, 42, 49, 50, 51, 52, 53, 55,
        56, 57, 63, 64],
       [ 6,  7,  8, 18, 20, 21, 24, 25, 32, 36, 37, 39, 44, 50, 55, 56,
        58, 60, 61, 66]])

In [69]:
x_next = scaler.transform(next)
x_next

next_Date = '2023-12-01 Evening';

In [77]:
y_next_pred = model.predict(np.array([x_next]))
print("The predicted numbers for the lottery game which will take place on",next_Date, "are (without rounding up):\n", scaler.inverse_transform(y_next_pred).astype(int)[0])

print("\n")
temp = np.array(scaler.inverse_transform(y_next_pred).astype(int)[0])
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("without rounding up")
print("winners:", duplicates)
print(len(duplicates)/20)

1/1 [==============================] - 0s 23ms/step
The predicted numbers for the lottery game which will take place on 2023-12-01 Evening are (without rounding up):
 [ 5  8  9 13 19 25 30 33 38 40 42 42 46 51 57 58 62 66 67 68]


without rounding up
winners: [ 8 25 42 58 66]
0.25


In [76]:
y_next_pred = model.predict(np.array([x_next]))
print("The predicted numbers for the lottery game which will take place on",next_Date, "are (with rounding up):\n", scaler.inverse_transform(y_next_pred).astype(int)[0]+1)

1/1 [==============================] - 0s 20ms/step
The predicted numbers for the lottery game which will take place on 2023-12-01 Evening are (with rounding up):
 [ 6  9 10 14 20 26 31 34 39 41 43 43 47 52 58 59 63 67 68 69]


In [73]:
temp = np.array(scaler.inverse_transform(y_next_pred).astype(int)[0]+1)
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("with rounding up")
print("winners:", duplicates)
print(len(duplicates)/20)

with rounding up
winners: [ 6 20 39 43 58]
0.25


In [74]:
to_predict_next = df.tail(3)
to_predict_next = np.array(to_predict_next)
to_predict_next

array([[ 7,  9, 12, 14, 16, 18, 20, 24, 25, 30, 34, 44, 45, 47, 49, 51,
        54, 59, 64, 70],
       [ 1,  3,  6,  7, 16, 20, 31, 35, 38, 42, 49, 50, 51, 52, 53, 55,
        56, 57, 63, 64],
       [ 6,  7,  8, 18, 20, 21, 24, 25, 32, 36, 37, 39, 44, 50, 55, 56,
        58, 60, 61, 66]])

In [75]:
scaled_to_predict_next = scaler.transform(to_predict_next)
y_pred_next = model.predict(np.array([scaled_to_predict_next]))
print("The predicted numbers for the next draw are:\n", scaler.inverse_transform(y_pred_next).astype(int)[0])

1/1 [==============================] - 0s 30ms/step
The predicted numbers for the next draw are:
 [ 4  7 10 12 19 21 24 26 30 32 37 39 42 48 52 54 59 62 66 68]
