<a href="https://colab.research.google.com/github/Snowdenstyll/keno/blob/main/Keno_Lottery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("/content/2023.csv")

In [3]:
df.head()

PlayDate AP  N01  N02  N03  N04  N05  N06  N07  N08  ...  N11  N12  N13  \
0  2023-01-01  A    3    7    9   14   19   21   22   30  ...   38   39   43   
1  2023-01-01  P    4    5   10   11   13   18   19   27  ...   37   41   43   
2  2023-01-02  P    2    3    4    7   15   24   25   30  ...   44   47   48   
3  2023-01-02  A    2    9   11   14   21   24   29   38  ...   47   48   50   
4  2023-01-03  P    1   10   15   17   26   34   37   40  ...   47   49   51   

   N14  N15  N16  N17  N18  N19  N20  
0   53   54   56   61   64   65   69  
1   44   47   48   55   58   63   70  
2   53   54   56   58   60   66   68  
3   57   58   59   60   61   66   70  
4   52   60   62   63   67   68   69  

[5 rows x 22 columns]

In [4]:
df.tail()

PlayDate AP  N01  N02  N03  N04  N05  N06  N07  N08  ...  N11  N12  \
662  2023-11-29  A    1    4    5    6   10   15   18   26  ...   42   45   
663  2023-11-29  P    1    4    6   10   12   15   17   19  ...   40   44   
664  2023-11-30  A    9   10   13   14   17   18   19   32  ...   40   47   
665  2023-11-30  P    1    4    6    7   10   12   14   15  ...   20   23   
666  2023-12-01  A    2    4   11   13   18   23   25   28  ...   35   36   

     N13  N14  N15  N16  N17  N18  N19  N20  
662   48   51   55   56   62   65   68   69  
663   46   47   51   54   56   57   60   68  
664   49   52   53   55   62   67   69   70  
665   25   40   43   44   47   61   62   63  
666   38   40   42   43   46   61   62   70  

[5 rows x 22 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   PlayDate  667 non-null    object
 1   AP        667 non-null    object
 2   N01       667 non-null    int64 
 3   N02       667 non-null    int64 
 4   N03       667 non-null    int64 
 5   N04       667 non-null    int64 
 6   N05       667 non-null    int64 
 7   N06       667 non-null    int64 
 8   N07       667 non-null    int64 
 9   N08       667 non-null    int64 
 10  N09       667 non-null    int64 
 11  N10       667 non-null    int64 
 12  N11       667 non-null    int64 
 13  N12       667 non-null    int64 
 14  N13       667 non-null    int64 
 15  N14       667 non-null    int64 
 16  N15       667 non-null    int64 
 17  N16       667 non-null    int64 
 18  N17       667 non-null    int64 
 19  N18       667 non-null    int64 
 20  N19       667 non-null    int64 
 21  N20       667 no

In [6]:
df.describe()

N01         N02         N03         N04         N05         N06  \
count  667.000000  667.000000  667.000000  667.000000  667.000000  667.000000   
mean     3.101949    6.410795    9.800600   13.073463   16.658171   20.266867   
std      2.352262    3.365931    4.126469    4.841543    5.387961    5.786556   
min      1.000000    2.000000    3.000000    4.000000    5.000000    8.000000   
25%      1.000000    4.000000    7.000000    9.000000   13.000000   16.000000   
50%      2.000000    6.000000    9.000000   12.000000   16.000000   20.000000   
75%      4.000000    8.000000   12.000000   16.000000   20.000000   24.000000   
max     15.000000   19.000000   27.000000   28.000000   35.000000   43.000000   

              N07         N08         N09         N10         N11         N12  \
count  667.000000  667.000000  667.000000  667.000000  667.000000  667.000000   
mean    23.689655   27.193403   30.632684   33.902549   37.254873   40.494753   
std      5.975520    5.918877    6.003378    6.003086    6.062323    6.115595   
min     11.000000   12.000000   14.000000   17.000000   20.000000   23.000000   
25%     20.000000   23.000000   26.000000   30.000000   33.000000   36.000000   
50%     23.000000   27.000000   31.000000   34.000000   37.000000   40.000000   
75%     27.500000   31.000000   34.500000   37.000000   41.000000   45.000000   
max     46.000000   47.000000   49.000000   51.000000   54.000000   57.000000   

              N13         N14         N15         N16         N17         N18  \
count  667.000000  667.000000  667.000000  667.000000  667.000000  667.000000   
mean    43.910045   47.488756   50.818591   53.985007   57.415292   60.727136   
std      5.924019    5.649772    5.492699    5.245597    4.741353    4.360335   
min     25.000000   31.000000   35.000000   37.000000   39.000000   40.000000   
25%     40.000000   44.000000   47.000000   50.000000   54.000000   58.000000   
50%     44.000000   48.000000   51.000000   55.000000   58.000000   61.000000   
75%     48.000000   52.000000   55.000000   58.000000   61.000000   64.000000   
max     58.000000   61.000000   62.000000   64.000000   67.000000   68.000000   

              N19         N20  
count  667.000000  667.000000  
mean    64.130435   67.670165  
std      3.702051    2.520021  
min     46.000000   58.000000  
25%     62.000000   66.000000  
50%     65.000000   68.000000  
75%     67.000000   70.000000  
max     69.000000   70.000000

In [7]:
df.drop(['PlayDate', 'AP'], axis=1, inplace=True)

In [8]:
df.head()

N01  N02  N03  N04  N05  N06  N07  N08  N09  N10  N11  N12  N13  N14  N15  \
0    3    7    9   14   19   21   22   30   32   34   38   39   43   53   54   
1    4    5   10   11   13   18   19   27   31   32   37   41   43   44   47   
2    2    3    4    7   15   24   25   30   38   39   44   47   48   53   54   
3    2    9   11   14   21   24   29   38   40   42   47   48   50   57   58   
4    1   10   15   17   26   34   37   40   42   44   47   49   51   52   60   

   N16  N17  N18  N19  N20  
0   56   61   64   65   69  
1   48   55   58   63   70  
2   56   58   60   66   68  
3   59   60   61   66   70  
4   62   63   67   68   69

In [9]:
scaler = StandardScaler().fit(df.values)
transformed_dataset = scaler.transform(df.values)
transformed_df = pd.DataFrame(data=transformed_dataset, index=df.index)

In [10]:
transformed_df.head()

0         1         2         3         4         5         6   \
0 -0.043373  0.175181 -0.194161  0.191516  0.434967  0.126791 -0.282975   
1  0.382068 -0.419454  0.048359 -0.428586 -0.679462 -0.392041 -0.785400   
2 -0.468815 -1.014089 -1.406760 -1.255389 -0.307986  0.645623  0.219450   
3 -0.468815  0.769816  0.290878  0.191516  0.806444  0.645623  0.889350   
4 -0.894257  1.067134  1.260958  0.811618  1.735135  2.375064  2.229150   

         7         8         9         10        11        12        13  \
0  0.474533  0.227929  0.016246  0.123003 -0.244600 -0.153735  0.976213   
1 -0.032700  0.061231 -0.317166 -0.042074  0.082678 -0.153735 -0.617967   
2  0.474533  1.228116  0.849776  1.113466  1.064513  0.690920  0.976213   
3  1.827155  1.561512  1.349894  1.608697  1.228152  1.028782  1.684738   
4  2.165311  1.894908  1.683306  1.608697  1.391791  1.197713  0.799082   

         14        15        16        17        18        19  
0  0.579642  0.384419  0.756619  0.751162  0.235064  0.528104  
1 -0.695734 -1.141814 -0.509792 -0.625911 -0.305583  0.925224  
2  0.579642  0.384419  0.123413 -0.166887  0.505387  0.130984  
3  1.308428  0.956756  0.545550  0.062626  0.505387  0.925224  
4  1.672820  1.529093  1.178756  1.439699  1.046033  0.528104

In [11]:
# All our games
number_of_rows = df.values.shape[0]
number_of_rows

667

In [12]:
# Amount of games we need to take into consideration for prediction
window_length = 7
window_length

7

In [13]:
# Balls counts
number_of_features = df.values.shape[1]
number_of_features

20

In [14]:
X = np.empty([ number_of_rows - window_length, window_length, number_of_features], dtype=float)
X

array([[[6.92344482e-310, 4.75101741e-310, 0.00000000e+000, ...,
         2.11519384e-319, 2.11534206e-319, 2.11549028e-319],
        [2.11563850e-319, 2.11578672e-319, 2.11593494e-319, ...,
         2.11830646e-319, 2.11845468e-319, 2.11860290e-319],
        [2.11875112e-319, 2.11889934e-319, 2.11904756e-319, ...,
         2.12151788e-319, 2.12166610e-319, 2.12181432e-319],
        ...,
        [2.12522338e-319, 2.12537160e-319, 2.12551981e-319, ...,
         2.12799014e-319, 2.12813836e-319, 2.12828658e-319],
        [2.12843480e-319, 2.12858302e-319, 2.12873124e-319, ...,
         2.13115216e-319, 2.13130038e-319, 2.13144860e-319],
        [2.13159682e-319, 2.13174504e-319, 2.13189326e-319, ...,
         2.13441300e-319, 2.13456122e-319, 2.13470944e-319]],

       [[2.13485766e-319, 2.13500588e-319, 2.13515410e-319, ...,
         2.13767383e-319, 2.13777264e-319, 2.13792086e-319],
        [2.13806908e-319, 2.13821730e-319, 2.13836552e-319, ...,
         2.14098407e-319, 2.14108288e-

In [15]:
y = np.empty([ number_of_rows - window_length, number_of_features], dtype=float)
y

array([[6.92344482e-310, 6.92344482e-310, 4.75101747e-310, ...,
        5.20461661e-090, 8.54510954e-072, 3.59650607e+179],
       [3.64464667e-086, 5.34508239e-038, 1.03080827e+136, ...,
        2.17597319e-076, 1.03080827e+136, 6.01347002e-154],
       [1.08481382e-042, 1.08539815e-071, 5.05230738e-038, ...,
        8.94213159e+130, 4.42323277e-062, 1.17941667e-095],
       ...,
       [7.12978069e+000, 1.08791182e-001, 1.08791182e-001, ...,
        5.42813151e+000, 2.78945085e+000, 1.76846135e+000],
       [1.34701105e+001, 1.34701105e+001, 5.42813151e+000, ...,
        2.18104404e+001, 1.76846135e+000, 1.76846135e+000],
       [1.76846135e+000, 3.21507702e+001, 4.49121017e-001, ...,
        5.42813151e+000, 5.42813151e+000, 2.78945085e+000]])

In [16]:
for i in range(0, number_of_rows-window_length):
    X[i] = transformed_df.iloc[i : i+window_length, 0 : number_of_features]
    y[i] = transformed_df.iloc[i+window_length : i+window_length+1, 0 : number_of_features]

In [17]:
X.shape

(660, 7, 20)

In [18]:
y.shape

(660, 20)

In [19]:
X[0]

array([[-0.04337338,  0.17518111, -0.19416128,  0.19151581,  0.43496724,
         0.12679107, -0.28297505,  0.47453305,  0.22792874,  0.01624571,
         0.12300345, -0.24459999, -0.15373482,  0.976213  ,  0.57964159,
         0.38441851,  0.75661905,  0.75116242,  0.23506368,  0.528104  ],
       [ 0.38206846, -0.41945402,  0.04835852, -0.42858635, -0.67946227,
        -0.3920411 , -0.78540014, -0.03270019,  0.06123086, -0.31716632,
        -0.04207361,  0.08267823, -0.15373482, -0.61796726, -0.6957338 ,
        -1.14181449, -0.50979226, -0.62591134, -0.30558279,  0.92522392],
       [-0.46881522, -1.01408914, -1.40676028, -1.25538922, -0.30798577,
         0.64562324,  0.21945004,  0.47453305,  1.22811604,  0.84977579,
         1.11346583,  1.06451289,  0.69092023,  0.976213  ,  0.57964159,
         0.38441851,  0.1234134 , -0.16688675,  0.50538692,  0.13098408],
       [-0.46881522,  0.76981624,  0.29087832,  0.19151581,  0.80644374,
         0.64562324,  0.88935016,  1.82715505,  

In [20]:
X[1]

array([[ 0.38206846, -0.41945402,  0.04835852, -0.42858635, -0.67946227,
        -0.3920411 , -0.78540014, -0.03270019,  0.06123086, -0.31716632,
        -0.04207361,  0.08267823, -0.15373482, -0.61796726, -0.6957338 ,
        -1.14181449, -0.50979226, -0.62591134, -0.30558279,  0.92522392],
       [-0.46881522, -1.01408914, -1.40676028, -1.25538922, -0.30798577,
         0.64562324,  0.21945004,  0.47453305,  1.22811604,  0.84977579,
         1.11346583,  1.06451289,  0.69092023,  0.976213  ,  0.57964159,
         0.38441851,  0.1234134 , -0.16688675,  0.50538692,  0.13098408],
       [-0.46881522,  0.76981624,  0.29087832,  0.19151581,  0.80644374,
         0.64562324,  0.88935016,  1.82715505,  1.56151181,  1.34989384,
         1.60869702,  1.228152  ,  1.02878225,  1.68473755,  1.30842752,
         0.95675588,  0.5455505 ,  0.06262554,  0.50538692,  0.92522392],
       [-0.89425705,  1.06713381,  1.26095753,  0.81161797,  1.735135  ,
         2.37506379,  2.2291504 ,  2.16531055,  

In [21]:
y[0]

array([-0.89425705, -0.71677158, -1.16424048, -1.0486885 ,  0.06349074,
        0.29973512, -0.11550002, -0.20177794, -0.43886279, -0.31716632,
        0.28808051,  0.08267823,  0.01519619, -0.44083612,  0.03305214,
        0.38441851,  1.17875615,  0.75116242,  1.04603339,  0.528104  ])

In [22]:
y[1]

array([1.23295213, 1.06713381, 0.77591792, 0.19151581, 0.99218199,
       0.64562324, 0.21945004, 0.3054553 , 0.22792874, 0.18295173,
       0.45315758, 0.40995645, 1.02878225, 0.62195072, 1.85501697,
       1.52909326, 1.17875615, 0.98067471, 1.31635662, 0.92522392])

In [144]:
# Recurrent Neural Netowrk (RNN) with Long Short Term Memory (LSTM)
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, Dropout
batch_size = 100

In [163]:
# Initialising the RNN
model = Sequential()
# Adding the input layer and the LSTM layer
model.add(Bidirectional(LSTM(210,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a first Dropout layer
model.add(Dropout(0.2))
# Adding a second LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a second Dropout layer
model.add(Dropout(0.2))
# Adding a third LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a fourth LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = False)))
# Adding a fourth Dropout layer
model.add(Dropout(0.2))
# Adding the first output layer
model.add(Dense(70))
# Adding the last output layer
model.add(Dense(number_of_features))

In [164]:
from tensorflow import keras
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.0001), loss ='mse', metrics=['accuracy'])

In [165]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9, random_state=90)

# Train the model
#history = model.fit(X_train, y_train, batch_size=100, epochs=400, verbose=2)
history = model.fit(X_train, y_train, batch_size=100, epochs=400, verbose=2)


Epoch 1/400
1/1 - 16s - loss: 0.9640 - accuracy: 0.0152 - 16s/epoch - 16s/step
Epoch 2/400
1/1 - 0s - loss: 0.9610 - accuracy: 0.0303 - 27ms/epoch - 27ms/step
Epoch 3/400
1/1 - 0s - loss: 0.9585 - accuracy: 0.0303 - 27ms/epoch - 27ms/step
Epoch 4/400
1/1 - 0s - loss: 0.9563 - accuracy: 0.0606 - 26ms/epoch - 26ms/step
Epoch 5/400
1/1 - 0s - loss: 0.9543 - accuracy: 0.1061 - 25ms/epoch - 25ms/step
Epoch 6/400
1/1 - 0s - loss: 0.9507 - accuracy: 0.0909 - 25ms/epoch - 25ms/step
Epoch 7/400
1/1 - 0s - loss: 0.9489 - accuracy: 0.1061 - 26ms/epoch - 26ms/step
Epoch 8/400
1/1 - 0s - loss: 0.9465 - accuracy: 0.1061 - 26ms/epoch - 26ms/step
Epoch 9/400
1/1 - 0s - loss: 0.9426 - accuracy: 0.1061 - 27ms/epoch - 27ms/step
Epoch 10/400
1/1 - 0s - loss: 0.9397 - accuracy: 0.1212 - 30ms/epoch - 30ms/step
Epoch 11/400
1/1 - 0s - loss: 0.9377 - accuracy: 0.1061 - 26ms/epoch - 26ms/step
Epoch 12/400
1/1 - 0s - loss: 0.9361 - accuracy: 0.1212 - 25ms/epoch - 25ms/step
Epoch 13/400
1/1 - 0s - loss: 0.9319 -

In [168]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=2)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

19/19 - 0s - loss: 0.3787 - accuracy: 0.2475 - 178ms/epoch - 9ms/step
Test Loss: 0.3787270486354828, Test Accuracy: 0.24747474491596222


In [167]:
#history = model.fit(X_train, y_train, batch_size=50, epochs=100, verbose=2)
history = model.fit(X_train, y_train, batch_size=50, epochs=100, verbose=2)

Epoch 1/100
14/14 - 0s - loss: 1.3323 - accuracy: 0.0818 - 257ms/epoch - 18ms/step
Epoch 2/100
14/14 - 0s - loss: 1.0137 - accuracy: 0.0955 - 199ms/epoch - 14ms/step
Epoch 3/100
14/14 - 0s - loss: 0.9875 - accuracy: 0.0788 - 192ms/epoch - 14ms/step
Epoch 4/100
14/14 - 0s - loss: 0.9768 - accuracy: 0.1045 - 192ms/epoch - 14ms/step
Epoch 5/100
14/14 - 0s - loss: 0.9704 - accuracy: 0.0924 - 186ms/epoch - 13ms/step
Epoch 6/100
14/14 - 0s - loss: 0.9657 - accuracy: 0.1136 - 195ms/epoch - 14ms/step
Epoch 7/100
14/14 - 0s - loss: 0.9614 - accuracy: 0.1136 - 189ms/epoch - 13ms/step
Epoch 8/100
14/14 - 0s - loss: 0.9567 - accuracy: 0.1000 - 191ms/epoch - 14ms/step
Epoch 9/100
14/14 - 0s - loss: 0.9505 - accuracy: 0.0985 - 189ms/epoch - 14ms/step
Epoch 10/100
14/14 - 0s - loss: 0.9491 - accuracy: 0.1061 - 186ms/epoch - 13ms/step
Epoch 11/100
14/14 - 0s - loss: 0.9402 - accuracy: 0.1197 - 206ms/epoch - 15ms/step
Epoch 12/100
14/14 - 0s - loss: 0.9377 - accuracy: 0.1288 - 191ms/epoch - 14ms/step
E

In [169]:
df1 = df.copy()
to_predict = df.tail(8)
to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)
to_predict

<ipython-input-169-427aa09c0e4b>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)


N01  N02  N03  N04  N05  N06  N07  N08  N09  N10  N11  N12  N13  N14  \
659    7    8   10   17   18   22   25   27   29   34   42   45   46   51   
660    2    3    4    9   19   20   22   23   36   39   41   48   54   55   
661    5    6    8    9   12   15   23   25   40   41   42   43   47   48   
662    1    4    5    6   10   15   18   26   31   33   42   45   48   51   
663    1    4    6   10   12   15   17   19   34   37   40   44   46   47   
664    9   10   13   14   17   18   19   32   34   39   40   47   49   52   
665    1    4    6    7   10   12   14   15   17   19   20   23   25   40   

     N15  N16  N17  N18  N19  N20  
659   55   56   59   62   64   67  
660   57   58   60   61   63   66  
661   49   56   57   63   65   66  
662   55   56   62   65   68   69  
663   51   54   56   57   60   68  
664   53   55   62   67   69   70  
665   43   44   47   61   62   63

In [170]:
to_predict = np.array(to_predict)
to_predict

array([[ 7,  8, 10, 17, 18, 22, 25, 27, 29, 34, 42, 45, 46, 51, 55, 56,
        59, 62, 64, 67],
       [ 2,  3,  4,  9, 19, 20, 22, 23, 36, 39, 41, 48, 54, 55, 57, 58,
        60, 61, 63, 66],
       [ 5,  6,  8,  9, 12, 15, 23, 25, 40, 41, 42, 43, 47, 48, 49, 56,
        57, 63, 65, 66],
       [ 1,  4,  5,  6, 10, 15, 18, 26, 31, 33, 42, 45, 48, 51, 55, 56,
        62, 65, 68, 69],
       [ 1,  4,  6, 10, 12, 15, 17, 19, 34, 37, 40, 44, 46, 47, 51, 54,
        56, 57, 60, 68],
       [ 9, 10, 13, 14, 17, 18, 19, 32, 34, 39, 40, 47, 49, 52, 53, 55,
        62, 67, 69, 70],
       [ 1,  4,  6,  7, 10, 12, 14, 15, 17, 19, 20, 23, 25, 40, 43, 44,
        47, 61, 62, 63]])

In [171]:
scaled_to_predict = scaler.transform(to_predict)

In [172]:
y_pred = model.predict(np.array([scaled_to_predict]))
print("The predicted numbers in the last lottery game are:", scaler.inverse_transform(y_pred).astype(int)[0])

1/1 [==============================] - 3s 3s/step
The predicted numbers in the last lottery game are: [ 2  4 10 15 22 26 26 29 31 31 33 35 37 40 44 44 50 59 61 68]


In [173]:
prediction = df.tail(1)
prediction = np.array(prediction)
print("The actual numbers in the last lottery game were:", prediction[0])

The actual numbers in the last lottery game were: [ 2  4 11 13 18 23 25 28 30 32 35 36 38 40 42 43 46 61 62 70]


In [174]:
temp = np.array(scaler.inverse_transform(y_pred).astype(int)[0])
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("winners:", duplicates)
print(len(duplicates)/20)

winners: [ 2  4 26 31 35 40 44 61]
0.4


In [175]:
next = df.copy()
next = next.tail((window_length))
next

N01  N02  N03  N04  N05  N06  N07  N08  N09  N10  N11  N12  N13  N14  \
660    2    3    4    9   19   20   22   23   36   39   41   48   54   55   
661    5    6    8    9   12   15   23   25   40   41   42   43   47   48   
662    1    4    5    6   10   15   18   26   31   33   42   45   48   51   
663    1    4    6   10   12   15   17   19   34   37   40   44   46   47   
664    9   10   13   14   17   18   19   32   34   39   40   47   49   52   
665    1    4    6    7   10   12   14   15   17   19   20   23   25   40   
666    2    4   11   13   18   23   25   28   30   32   35   36   38   40   

     N15  N16  N17  N18  N19  N20  
660   57   58   60   61   63   66  
661   49   56   57   63   65   66  
662   55   56   62   65   68   69  
663   51   54   56   57   60   68  
664   53   55   62   67   69   70  
665   43   44   47   61   62   63  
666   42   43   46   61   62   70

In [177]:
next = np.array(next)
next

array([[ 2,  3,  4,  9, 19, 20, 22, 23, 36, 39, 41, 48, 54, 55, 57, 58,
        60, 61, 63, 66],
       [ 5,  6,  8,  9, 12, 15, 23, 25, 40, 41, 42, 43, 47, 48, 49, 56,
        57, 63, 65, 66],
       [ 1,  4,  5,  6, 10, 15, 18, 26, 31, 33, 42, 45, 48, 51, 55, 56,
        62, 65, 68, 69],
       [ 1,  4,  6, 10, 12, 15, 17, 19, 34, 37, 40, 44, 46, 47, 51, 54,
        56, 57, 60, 68],
       [ 9, 10, 13, 14, 17, 18, 19, 32, 34, 39, 40, 47, 49, 52, 53, 55,
        62, 67, 69, 70],
       [ 1,  4,  6,  7, 10, 12, 14, 15, 17, 19, 20, 23, 25, 40, 43, 44,
        47, 61, 62, 63],
       [ 2,  4, 11, 13, 18, 23, 25, 28, 30, 32, 35, 36, 38, 40, 42, 43,
        46, 61, 62, 70]])

In [178]:
x_next = scaler.transform(next)
x_next

next_Date = '2023-12-01 Evening';

In [179]:
y_next_pred = model.predict(np.array([x_next]))
print("The predicted numbers for the lottery game which will take place on",next_Date, "are (without rounding up):\n", scaler.inverse_transform(y_next_pred).astype(int)[0])

print("\n")
temp = np.array(scaler.inverse_transform(y_next_pred).astype(int)[0])
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("without rounding up")
print("winners:", duplicates)
print(len(duplicates)/20)

1/1 [==============================] - 0s 21ms/step
The predicted numbers for the lottery game which will take place on 2023-12-01 Evening are (without rounding up):
 [ 0  2  7 10 17 20 23 25 29 31 36 39 41 43 46 46 51 59 62 69]


without rounding up
winners: [ 2 23 25 36 43 46 62]
0.35


In [180]:
y_next_pred = model.predict(np.array([x_next]))
print("The predicted numbers for the lottery game which will take place on",next_Date, "are (with rounding up):\n", scaler.inverse_transform(y_next_pred).astype(int)[0]+1)

1/1 [==============================] - 0s 24ms/step
The predicted numbers for the lottery game which will take place on 2023-12-01 Evening are (with rounding up):
 [ 1  3  8 11 18 21 24 26 30 32 37 40 42 44 47 47 52 60 63 70]


In [181]:
temp = np.array(scaler.inverse_transform(y_next_pred).astype(int)[0]+1)
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("with rounding up")
print("winners:", duplicates)
print(len(duplicates)/20)

with rounding up
winners: [11 18 30 32 40 42 47 70]
0.4


In [182]:
to_predict_next = df.tail(8)
to_predict_next = np.array(to_predict_next)
to_predict_next

array([[ 7,  8, 10, 17, 18, 22, 25, 27, 29, 34, 42, 45, 46, 51, 55, 56,
        59, 62, 64, 67],
       [ 2,  3,  4,  9, 19, 20, 22, 23, 36, 39, 41, 48, 54, 55, 57, 58,
        60, 61, 63, 66],
       [ 5,  6,  8,  9, 12, 15, 23, 25, 40, 41, 42, 43, 47, 48, 49, 56,
        57, 63, 65, 66],
       [ 1,  4,  5,  6, 10, 15, 18, 26, 31, 33, 42, 45, 48, 51, 55, 56,
        62, 65, 68, 69],
       [ 1,  4,  6, 10, 12, 15, 17, 19, 34, 37, 40, 44, 46, 47, 51, 54,
        56, 57, 60, 68],
       [ 9, 10, 13, 14, 17, 18, 19, 32, 34, 39, 40, 47, 49, 52, 53, 55,
        62, 67, 69, 70],
       [ 1,  4,  6,  7, 10, 12, 14, 15, 17, 19, 20, 23, 25, 40, 43, 44,
        47, 61, 62, 63],
       [ 2,  4, 11, 13, 18, 23, 25, 28, 30, 32, 35, 36, 38, 40, 42, 43,
        46, 61, 62, 70]])

In [183]:
scaled_to_predict_next = scaler.transform(to_predict_next)
y_pred_next = model.predict(np.array([scaled_to_predict_next]))
print("The predicted numbers for the next draw are:\n", scaler.inverse_transform(y_pred_next).astype(int)[0])

1/1 [==============================] - 5s 5s/step
The predicted numbers for the next draw are:
 [ 2  3  7 12 19 21 22 25 27 29 32 35 37 39 43 42 45 54 58 68]
