<a href="https://colab.research.google.com/github/Snowdenstyll/keno/blob/main/Ontario_DailyKeno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New section

In [12]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [13]:
df = pd.read_csv("/content/keno_2020.csv")

In [14]:
df.head()

PlayDate AP  N01  N02  N03  N04  N05  N06  N07  N08  ...  N11  N12  N13  \
0  2020-05-09  P    1   10   12   15   19   20   25   26  ...   36   37   40   
1  2020-05-09  A    4    7    8   17   18   20   21   28  ...   39   41   48   
2  2020-05-08  P    4    5    7    8    9   14   15   26  ...   32   35   43   
3  2020-05-08  A    2    4    6    7    9   10   14   30  ...   38   40   42   
4  2020-05-07  P    6   14   15   17   18   22   25   26  ...   32   35   36   

   N14  N15  N16  N17  N18  N19  N20  
0   46   47   48   53   58   59   64  
1   50   58   59   60   63   67   70  
2   48   53   58   61   63   68   69  
3   48   49   50   55   59   65   68  
4   37   55   57   59   63   68   69  

[5 rows x 22 columns]

In [15]:
df.tail()

PlayDate AP  N01  N02  N03  N04  N05  N06  N07  N08  ...  N11  N12  \
11651  1996-05-03  P    3    8   20   26   27   32   36   38  ...   45   47   
11652  1996-05-02  P    4    5    7   11   13   15   19   23  ...   28   35   
11653  1996-05-01  P    2    3    5    7   11   14   15   20  ...   46   47   
11654  1996-04-30  P    6    7   10   17   23   24   27   28  ...   42   43   
11655  1996-04-29  P    1    2    4    6    9   13   15   16  ...   34   37   

       N13  N14  N15  N16  N17  N18  N19  N20  
11651   50   53   54   56   59   61   67   68  
11652   38   40   48   50   57   58   64   66  
11653   48   52   56   61   62   63   66   70  
11654   46   48   50   55   60   61   67   70  
11655   41   48   50   52   53   54   57   68  

[5 rows x 22 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11656 entries, 0 to 11655
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   PlayDate  11656 non-null  object
 1   AP        11656 non-null  object
 2   N01       11656 non-null  int64 
 3   N02       11656 non-null  int64 
 4   N03       11656 non-null  int64 
 5   N04       11656 non-null  int64 
 6   N05       11656 non-null  int64 
 7   N06       11656 non-null  int64 
 8   N07       11656 non-null  int64 
 9   N08       11656 non-null  int64 
 10  N09       11656 non-null  int64 
 11  N10       11656 non-null  int64 
 12  N11       11656 non-null  int64 
 13  N12       11656 non-null  int64 
 14  N13       11656 non-null  int64 
 15  N14       11656 non-null  int64 
 16  N15       11656 non-null  int64 
 17  N16       11656 non-null  int64 
 18  N17       11656 non-null  int64 
 19  N18       11656 non-null  int64 
 20  N19       11656 non-null  int64 
 21  N20       11

In [17]:
df.describe()

N01           N02           N03           N04           N05  \
count  11656.000000  11656.000000  11656.000000  11656.000000  11656.000000   
mean       3.359815      6.768102     10.167982     13.613161     17.044441   
std        2.690641      3.752925      4.490355      5.066378      5.481070   
min        1.000000      2.000000      3.000000      4.000000      5.000000   
25%        1.000000      4.000000      7.000000     10.000000     13.000000   
50%        3.000000      6.000000      9.000000     13.000000     17.000000   
75%        5.000000      9.000000     13.000000     17.000000     21.000000   
max       21.000000     31.000000     34.000000     40.000000     42.000000   

                N06           N07           N08           N09           N10  \
count  11656.000000  11656.000000  11656.000000  11656.000000  11656.000000   
mean      20.527111     23.915752     27.311170     30.662749     34.041695   
std        5.804977      6.016132      6.149799      6.205803      6.289005   
min        6.000000      7.000000      9.000000     10.000000     13.000000   
25%       16.000000     20.000000     23.000000     26.000000     30.000000   
50%       20.000000     24.000000     27.000000     31.000000     34.000000   
75%       24.000000     28.000000     31.000000     35.000000     38.000000   
max       44.000000     47.000000     50.000000     53.000000     55.000000   

                N11           N12           N13           N14           N15  \
count  11656.000000  11656.000000  11656.000000  11656.000000  11656.000000   
mean      37.405714     40.769904     44.116335     47.441146     50.778226   
std        6.247329      6.155966      6.063982      5.886716      5.667293   
min       15.000000     18.000000     21.000000     23.000000     28.000000   
25%       33.000000     37.000000     40.000000     44.000000     47.000000   
50%       37.000000     41.000000     44.000000     48.000000     51.000000   
75%       42.000000     45.000000     48.000000     52.000000     55.000000   
max       57.000000     60.000000     62.000000     63.000000     65.000000   

                N16           N17           N18           N19           N20  
count  11656.000000  11656.000000  11656.000000  11656.000000  11656.000000  
mean      54.183854     57.561084     60.890786     64.245024     67.591798  
std        5.344205      4.884426      4.376314      3.701777      2.723490  
min       32.000000     35.000000     36.000000     44.000000     48.000000  
25%       51.000000     55.000000     58.000000     62.000000     66.000000  
50%       55.000000     58.000000     62.000000     65.000000     68.000000  
75%       58.000000     61.000000     64.000000     67.000000     70.000000  
max       66.000000     67.000000     68.000000     69.000000     70.000000

In [18]:
df.drop(['PlayDate', 'AP'], axis=1, inplace=True)

In [19]:
df.head()

N01  N02  N03  N04  N05  N06  N07  N08  N09  N10  N11  N12  N13  N14  N15  \
0    1   10   12   15   19   20   25   26   27   30   36   37   40   46   47   
1    4    7    8   17   18   20   21   28   31   38   39   41   48   50   58   
2    4    5    7    8    9   14   15   26   29   30   32   35   43   48   53   
3    2    4    6    7    9   10   14   30   32   36   38   40   42   48   49   
4    6   14   15   17   18   22   25   26   27   29   32   35   36   37   55   

   N16  N17  N18  N19  N20  
0   48   53   58   59   64  
1   59   60   63   67   70  
2   58   61   63   68   69  
3   50   55   59   65   68  
4   57   59   63   68   69

In [20]:
scaler = StandardScaler().fit(df.values)
transformed_dataset = scaler.transform(df.values)
transformed_df = pd.DataFrame(data=transformed_dataset, index=df.index)

In [21]:
transformed_df.tail()

0         1         2         3         4         5         6   \
11651 -0.133734  0.328264  2.189680  2.445015  1.816431  1.976473  2.008727   
11652  0.237941 -0.471147 -0.705538 -0.515807 -0.737924 -0.952174 -0.817130   
11653 -0.505409 -1.004087 -1.150957 -1.305359 -1.102832 -1.124447 -1.482038   
11654  0.981290  0.061794 -0.037411  0.668522  1.086615  0.598286  0.512685   
11655 -0.877083 -1.270558 -1.373666 -1.502747 -1.467740 -1.296721 -1.482038   

             7         8         9         10        11        12        13  \
11651  1.738153  1.343518  1.424500  1.215657  1.012085  0.970306  0.944345   
11652 -0.701056 -1.073678 -1.119732 -1.505622 -0.937327 -1.008677 -1.264112   
11653 -1.188898 -0.429092  1.742529  1.375733  1.012085  0.640475  0.774464   
11654  0.112013  0.054347  0.788442  0.735432  0.362281  0.310645  0.094939   
11655 -1.839354 -1.557117 -0.960717 -0.545171 -0.612425 -0.513931  0.094939   

             14        15        16        17        18        19  
11651  0.568510  0.339849  0.294605  0.024957  0.744263  0.149888  
11652 -0.490242 -0.782910 -0.114877 -0.660581 -0.066194 -0.584495  
11653  0.921427  1.275482  0.908829  0.481982  0.474111  0.884272  
11654 -0.137325  0.152723  0.499346  0.024957  0.744263  0.884272  
11655 -0.137325 -0.408657 -0.933842 -1.574632 -1.957259  0.149888

In [22]:
# All our games
number_of_rows = df.values.shape[0]
number_of_rows

11656

In [23]:
# Amount of games we need to take into consideration for prediction
window_length = 10
window_length

10

In [24]:
# Balls counts
number_of_features = df.values.shape[1]
number_of_features

20

In [25]:
X = np.empty([ number_of_rows - window_length, window_length, number_of_features], dtype=float)
X

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [26]:
y = np.empty([ number_of_rows - window_length, number_of_features], dtype=float)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [27]:
for i in range(0, number_of_rows-window_length):
    X[i] = transformed_df.iloc[i : i+window_length, 0 : number_of_features]
    y[i] = transformed_df.iloc[i+window_length : i+window_length+1, 0 : number_of_features]

In [28]:
X.shape

(11646, 10, 20)

In [29]:
y.shape

(11646, 20)

In [30]:
X[0]

array([[-0.8770832 ,  0.86120473,  0.40800706,  0.27374563,  0.35679955,
        -0.09080709,  0.18023124, -0.21321453, -0.59023883, -0.64268808,
        -0.22502002, -0.61242473, -0.67884625, -0.24482379, -0.66670066,
        -1.15716342, -0.93384162, -0.66058105, -1.41695451, -1.31887842],
       [ 0.23794062,  0.06179386, -0.48282938,  0.66852187,  0.17434559,
        -0.09080709, -0.4846763 ,  0.11201331,  0.05434682,  0.62942778,
         0.2552058 ,  0.03737934,  0.64047545,  0.43470141,  1.2743446 ,
         0.90122897,  0.49934635,  0.48198205,  0.74426268,  0.88427166],
       [ 0.23794062, -0.47114672, -0.70553849, -1.10797124, -1.46774006,
        -1.12444717, -1.48203761, -0.21321453, -0.267946  , -0.64268808,
        -0.86532112, -0.93732676, -0.18410061,  0.09493881,  0.3920513 ,
         0.71410239,  0.70408749,  0.48198205,  1.01441483,  0.51707998],
       [-0.50540859, -0.73761702, -0.9282476 , -1.30535936, -1.46774006,
        -1.81354056, -1.64826449,  0.43724116,  

In [31]:
X[1]

array([[ 0.23794062,  0.06179386, -0.48282938,  0.66852187,  0.17434559,
        -0.09080709, -0.4846763 ,  0.11201331,  0.05434682,  0.62942778,
         0.2552058 ,  0.03737934,  0.64047545,  0.43470141,  1.2743446 ,
         0.90122897,  0.49934635,  0.48198205,  0.74426268,  0.88427166],
       [ 0.23794062, -0.47114672, -0.70553849, -1.10797124, -1.46774006,
        -1.12444717, -1.48203761, -0.21321453, -0.267946  , -0.64268808,
        -0.86532112, -0.93732676, -0.18410061,  0.09493881,  0.3920513 ,
         0.71410239,  0.70408749,  0.48198205,  1.01441483,  0.51707998],
       [-0.50540859, -0.73761702, -0.9282476 , -1.30535936, -1.46774006,
        -1.81354056, -1.64826449,  0.43724116,  0.21549323,  0.31139881,
         0.09513053, -0.12507167, -0.34901583,  0.09493881, -0.31378334,
        -0.78291026, -0.52435934, -0.43206843,  0.20395838,  0.1498883 ],
       [ 0.98128984,  1.92708589,  1.07613439,  0.66852187,  0.17434559,
         0.2537396 ,  0.18023124, -0.21321453, -

In [32]:
y[0]

array([ 1.35296445,  0.59473444, -0.03741116, -0.31841874,  0.17434559,
       -0.09080709, -0.4846763 , -0.86367022, -1.23482447, -0.80170256,
       -0.86532112,  0.03737934, -0.34901583, -0.07494249, -0.490242  ,
       -0.4086571 , -0.93384162, -0.88909368, -0.06619377, -0.21730338])

In [33]:
y[1]

array([ 0.23794062,  0.06179386, -0.26012027,  0.0763575 ,  0.35679955,
        0.08146626,  0.01400436, -0.21321453, -0.42909241, -0.32465911,
       -0.22502002, -0.28752269, -0.51393104, -0.58458638, -0.66670066,
       -0.4086571 , -0.93384162, -1.34611892, -1.41695451, -0.95168674])

In [34]:
# Recurrent Neural Netowrk (RNN) with Long Short Term Memory (LSTM)
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, Dropout
batch_size = 100

In [35]:
# Initialising the RNN
model = Sequential()
# Adding the input layer and the LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a first Dropout layer
model.add(Dropout(0.2))
# Adding a second LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a second Dropout layer
model.add(Dropout(0.2))
# Adding a third LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a fourth LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = False)))
# Adding a fourth Dropout layer
model.add(Dropout(0.2))
# Adding the first output layer
model.add(Dense(60))
# Adding the last output layer
model.add(Dense(number_of_features))

In [36]:
from tensorflow import keras
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.0001), loss ='mse', metrics=['accuracy'])

In [38]:
history = model.fit(x=X, y=y, batch_size=100, epochs=500, verbose=2)

Epoch 1/500
117/117 - 17s - loss: 1.0012 - accuracy: 0.0564 - 17s/epoch - 142ms/step
Epoch 2/500
117/117 - 2s - loss: 1.0001 - accuracy: 0.0557 - 2s/epoch - 19ms/step
Epoch 3/500
117/117 - 2s - loss: 0.9997 - accuracy: 0.0635 - 2s/epoch - 16ms/step
Epoch 4/500
117/117 - 2s - loss: 0.9994 - accuracy: 0.0601 - 2s/epoch - 16ms/step
Epoch 5/500
117/117 - 2s - loss: 0.9989 - accuracy: 0.0661 - 2s/epoch - 17ms/step
Epoch 6/500
117/117 - 2s - loss: 0.9990 - accuracy: 0.0606 - 2s/epoch - 18ms/step
Epoch 7/500
117/117 - 2s - loss: 0.9987 - accuracy: 0.0634 - 2s/epoch - 17ms/step
Epoch 8/500
117/117 - 2s - loss: 0.9983 - accuracy: 0.0678 - 2s/epoch - 20ms/step
Epoch 9/500
117/117 - 2s - loss: 0.9980 - accuracy: 0.0633 - 2s/epoch - 18ms/step
Epoch 10/500
117/117 - 2s - loss: 0.9977 - accuracy: 0.0645 - 2s/epoch - 16ms/step
Epoch 11/500
117/117 - 2s - loss: 0.9972 - accuracy: 0.0748 - 2s/epoch - 16ms/step
Epoch 12/500
117/117 - 2s - loss: 0.9966 - accuracy: 0.0698 - 2s/epoch - 16ms/step
Epoch 13/5

In [39]:
#Save The Model
import datetime

date = datetime.datetime.now()
version = (date.strftime("%y_%m_%d_%f")) + "\n"
prefix_model_version = 'on_keno_model_'
model_version = prefix_model_version + version

f = open("/logs/modelversions.txt", "a")
f.write(model_version + str(history.history) + "\n\n")
f.close()

model.save(model_version + ".keras");

FileNotFoundError: ignored

In [104]:
to_predict = df.head(8)
to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)
to_predict

<ipython-input-104-212162c40eef>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)


N01  N02  N03  N04  N05  N06  N07  N08  N09  N10  N11  N12  N13  N14  N15  \
0    1   10   12   15   19   20   25   26   27   30   36   37   40   46   47   
1    4    7    8   17   18   20   21   28   31   38   39   41   48   50   58   
2    4    5    7    8    9   14   15   26   29   30   32   35   43   48   53   
3    2    4    6    7    9   10   14   30   32   36   38   40   42   48   49   
4    6   14   15   17   18   22   25   26   27   29   32   35   36   37   55   
5    5    6    7    9   13   28   32   39   41   43   50   51   53   56   57   
6    1    6    8    9   11   20   23   24   25   28   29   32   33   35   41   

   N16  N17  N18  N19  N20  
0   48   53   58   59   64  
1   59   60   63   67   70  
2   58   61   63   68   69  
3   50   55   59   65   68  
4   57   59   63   68   69  
5   62   63   65   67   69  
6   44   47   60   65   68

In [105]:
to_predict = np.array(to_predict)
to_predict

array([[ 1, 10, 12, 15, 19, 20, 25, 26, 27, 30, 36, 37, 40, 46, 47, 48,
        53, 58, 59, 64],
       [ 4,  7,  8, 17, 18, 20, 21, 28, 31, 38, 39, 41, 48, 50, 58, 59,
        60, 63, 67, 70],
       [ 4,  5,  7,  8,  9, 14, 15, 26, 29, 30, 32, 35, 43, 48, 53, 58,
        61, 63, 68, 69],
       [ 2,  4,  6,  7,  9, 10, 14, 30, 32, 36, 38, 40, 42, 48, 49, 50,
        55, 59, 65, 68],
       [ 6, 14, 15, 17, 18, 22, 25, 26, 27, 29, 32, 35, 36, 37, 55, 57,
        59, 63, 68, 69],
       [ 5,  6,  7,  9, 13, 28, 32, 39, 41, 43, 50, 51, 53, 56, 57, 62,
        63, 65, 67, 69],
       [ 1,  6,  8,  9, 11, 20, 23, 24, 25, 28, 29, 32, 33, 35, 41, 44,
        47, 60, 65, 68]])

In [106]:
scaled_to_predict = scaler.transform(to_predict)

In [107]:
y_pred = model.predict(np.array([scaled_to_predict]))
print("The predicted numbers in the last lottery game are:", scaler.inverse_transform(y_pred).astype(int)[0])

1/1 [==============================] - 0s 24ms/step
The predicted numbers in the last lottery game are: [ 3  7 11 14 17 19 24 26 28 32 38 43 46 50 52 54 58 61 64 66]


In [103]:
prediction = df.head(7)
prediction = np.array(prediction)
print("The actual numbers in the last lottery game were:", prediction[0])

The actual numbers in the last lottery game were: [ 1 10 12 15 19 20 25 26 27 30 36 37 40 46 47 48 53 58 59 64]
