<a href="https://colab.research.google.com/github/Snowdenstyll/keno/blob/main/DailyGrand.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [14]:
df = pd.read_csv("/content/2023.csv")

In [15]:
df.head()

PlayDate  N01  N02  N03  N04  N05  N06
0  2023-01-02    2   19   20   27   47    5
1  2023-01-05    1   27   32   33   35    4
2  2023-01-09    5   13   15   22   45    6
3  2023-01-12    4    7   27   33   48    7
4  2023-01-16   14   19   21   36   48    1

In [16]:
df.tail()

PlayDate  N01  N02  N03  N04  N05  N06
92  2023-11-20    3   36   38   42   48    6
93  2023-11-23    1   12   14   20   31    4
94  2023-11-27   13   16   18   27   30    6
95  2023-11-30   31   32   34   39   49    6
96  2023-12-04    1    8   11   26   37    2

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   PlayDate  97 non-null     object
 1   N01       97 non-null     int64 
 2   N02       97 non-null     int64 
 3   N03       97 non-null     int64 
 4   N04       97 non-null     int64 
 5   N05       97 non-null     int64 
 6   N06       97 non-null     int64 
dtypes: int64(6), object(1)
memory usage: 5.4+ KB


In [18]:
df.describe()

N01        N02        N03        N04        N05        N06
count  97.000000  97.000000  97.000000  97.000000  97.000000  97.000000
mean    7.752577  16.051546  22.958763  31.835052  40.835052   4.247423
std     6.301506   7.734354   7.897676   8.016494   7.156990   2.005362
min     1.000000   2.000000   8.000000  13.000000  20.000000   1.000000
25%     3.000000  10.000000  17.000000  26.000000  37.000000   2.000000
50%     6.000000  15.000000  23.000000  33.000000  43.000000   5.000000
75%    12.000000  21.000000  28.000000  38.000000  47.000000   6.000000
max    31.000000  39.000000  44.000000  47.000000  49.000000   7.000000

In [19]:
df.drop(['PlayDate'], axis=1, inplace=True)

In [20]:
df.head()

N01  N02  N03  N04  N05  N06
0    2   19   20   27   47    5
1    1   27   32   33   35    4
2    5   13   15   22   45    6
3    4    7   27   33   48    7
4   14   19   21   36   48    1

In [21]:
scaler = StandardScaler().fit(df.values)
transformed_dataset = scaler.transform(df.values)
transformed_df = pd.DataFrame(data=transformed_dataset, index=df.index)

In [22]:
transformed_df.head()

0         1         2         3         4         5
0 -0.917632  0.383196 -0.376583 -0.606271  0.865863  0.377232
1 -1.077148  1.422915  1.150744  0.146074 -0.819529 -0.124021
2 -0.439082 -0.396594 -1.012970 -1.233225  0.584964  0.878486
3 -0.598598 -1.176384  0.514358  0.146074  1.006313  1.379739
4  0.996568  0.383196 -0.249306  0.522246  1.006313 -1.627782

In [23]:
# All our games
number_of_rows = df.values.shape[0]
number_of_rows

97

In [64]:
# Amount of games we need to take into consideration for prediction
window_length = 5
window_length

5

In [65]:
# Balls counts
number_of_features = df.values.shape[1]
number_of_features

6

In [66]:
X = np.empty([ number_of_rows - window_length, window_length, number_of_features], dtype=float)
X

array([[[4.70544040e-310, 4.70544427e-310, 4.70544040e-310,
         4.70544427e-310, 6.92035252e-310, 0.00000000e+000],
        [4.70544308e-310, 0.00000000e+000, 3.95252517e-322,
         3.95252517e-322, 4.70487965e-310, 4.44659081e-323],
        [6.80276457e+199, 5.73116149e-322, 6.92035252e-310,
         0.00000000e+000, 3.95252517e-323, 0.00000000e+000],
        [0.00000000e+000, 4.35271834e-321, 4.70544339e-310,
         4.70544385e-310, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 4.24399158e-314,
         4.70544405e-310, 4.70531347e-310, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00

In [67]:
y = np.empty([ number_of_rows - window_length, number_of_features], dtype=float)
y

array([[4.70544309e-310, 4.70544375e-310, 4.70544309e-310,
        4.70544375e-310, 4.70487951e-310, 3.65608578e-322],
       [3.65608578e-322, 4.70544091e-310, 3.95252517e-322,
        3.95252517e-322, 4.70487951e-310, 9.88131292e-323],
       [9.88131292e-323, 0.00000000e+000, 6.92035252e-310,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 2.37645576e-321, 4.70544407e-310,
        4.70544407e-310, 1.58101007e-322, 2.37151510e-322],
       [4.70487905e-310, 3.21142670e-322, 3.21142670e-322,
        0.00000000e+000, 3.95252517e-322, 3.95252517e-322],
       [4.70487905e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 4.70544096e-310,
        7.95445690e-322, 4.70544384e-310, 4.70544407e-310],
       [8.79322021e+199, 6.10103417e-310, 2.15253881e-312,
        2.42092166e-322, 4.70544112e-310, 6.92041876e-310],
       [2.17388884e-322, 0.00000000e+000, 4.7430

In [68]:
for i in range(0, number_of_rows-window_length):
    X[i] = transformed_df.iloc[i : i+window_length, 0 : number_of_features]
    y[i] = transformed_df.iloc[i+window_length : i+window_length+1, 0 : number_of_features]

In [69]:
X.shape

(92, 5, 6)

In [70]:
y.shape

(92, 6)

In [71]:
X[0]

array([[-0.9176316 ,  0.38319559, -0.37658335, -0.60627113,  0.86586319,
         0.37723202],
       [-1.07714821,  1.4229151 ,  1.15074425,  0.14607385, -0.81952938,
        -0.12402149],
       [-0.43908179, -0.39659404, -1.01296985, -1.23322529,  0.58496443,
         0.87848552],
       [-0.59859839, -1.17638367,  0.51435775,  0.14607385,  1.00631257,
         1.37973902],
       [ 0.99656766,  0.38319559, -0.24930605,  0.52224635,  1.00631257,
        -1.62778199]])

In [72]:
X[1]

array([[-1.07714821,  1.4229151 ,  1.15074425,  0.14607385, -0.81952938,
        -0.12402149],
       [-0.43908179, -0.39659404, -1.01296985, -1.23322529,  0.58496443,
         0.87848552],
       [-0.59859839, -1.17638367,  0.51435775,  0.14607385,  1.00631257,
         1.37973902],
       [ 0.99656766,  0.38319559, -0.24930605,  0.52224635,  1.00631257,
        -1.62778199],
       [-0.12004858, -0.91645379,  0.00524855,  0.27146469,  0.30406567,
         0.37723202]])

In [73]:
y[0]

array([-0.12004858, -0.91645379,  0.00524855,  0.27146469,  0.30406567,
        0.37723202])

In [74]:
y[1]

array([ 1.31560086,  0.38319559, -0.12202875,  0.64763718,  0.44451505,
        0.37723202])

In [75]:
# Recurrent Neural Netowrk (RNN) with Long Short Term Memory (LSTM)
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, Dropout
batch_size = 100

In [76]:
# Initialising the RNN
model = Sequential()
# Adding the input layer and the LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a first Dropout layer
model.add(Dropout(0.2))
# Adding a second LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a second Dropout layer
model.add(Dropout(0.2))
# Adding a third LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a fourth LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = False)))
# Adding a fourth Dropout layer
model.add(Dropout(0.2))
# Adding the first output layer
model.add(Dense(49))
# Adding the last output layer
model.add(Dense(number_of_features))

In [77]:
from tensorflow import keras
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.0001), loss ='mse', metrics=['accuracy'])

In [78]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9, random_state=90)

# Train the model
#history = model.fit(X_train, y_train, batch_size=100, epochs=400, verbose=2)
history = model.fit(X_train, y_train, batch_size=100, epochs=400, verbose=2)


Epoch 1/400
1/1 - 16s - loss: 0.9337 - accuracy: 0.0000e+00 - 16s/epoch - 16s/step
Epoch 2/400
1/1 - 0s - loss: 0.9247 - accuracy: 0.1111 - 25ms/epoch - 25ms/step
Epoch 3/400
1/1 - 0s - loss: 0.9234 - accuracy: 0.2222 - 24ms/epoch - 24ms/step
Epoch 4/400
1/1 - 0s - loss: 0.9139 - accuracy: 0.5556 - 20ms/epoch - 20ms/step
Epoch 5/400
1/1 - 0s - loss: 0.9112 - accuracy: 0.5556 - 18ms/epoch - 18ms/step
Epoch 6/400
1/1 - 0s - loss: 0.9060 - accuracy: 0.7778 - 19ms/epoch - 19ms/step
Epoch 7/400
1/1 - 0s - loss: 0.8988 - accuracy: 0.5556 - 20ms/epoch - 20ms/step
Epoch 8/400
1/1 - 0s - loss: 0.8905 - accuracy: 0.6667 - 19ms/epoch - 19ms/step
Epoch 9/400
1/1 - 0s - loss: 0.8888 - accuracy: 0.6667 - 18ms/epoch - 18ms/step
Epoch 10/400
1/1 - 0s - loss: 0.8754 - accuracy: 0.6667 - 27ms/epoch - 27ms/step
Epoch 11/400
1/1 - 0s - loss: 0.8733 - accuracy: 0.6667 - 19ms/epoch - 19ms/step
Epoch 12/400
1/1 - 0s - loss: 0.8640 - accuracy: 0.6667 - 22ms/epoch - 22ms/step
Epoch 13/400
1/1 - 0s - loss: 0.85

In [79]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=2)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

3/3 - 4s - loss: 2.0581 - accuracy: 0.2651 - 4s/epoch - 1s/step
Test Loss: 2.0581212043762207, Test Accuracy: 0.2650602459907532


In [49]:
#history = model.fit(X_train, y_train, batch_size=50, epochs=100, verbose=2)
history = model.fit(X_train, y_train, batch_size=50, epochs=100, verbose=2)

Epoch 1/100
1/1 - 0s - loss: 0.0081 - accuracy: 1.0000 - 20ms/epoch - 20ms/step
Epoch 2/100
1/1 - 0s - loss: 0.0074 - accuracy: 0.7778 - 18ms/epoch - 18ms/step
Epoch 3/100
1/1 - 0s - loss: 0.0116 - accuracy: 1.0000 - 17ms/epoch - 17ms/step
Epoch 4/100
1/1 - 0s - loss: 0.0085 - accuracy: 1.0000 - 17ms/epoch - 17ms/step
Epoch 5/100
1/1 - 0s - loss: 0.0071 - accuracy: 0.8889 - 17ms/epoch - 17ms/step
Epoch 6/100
1/1 - 0s - loss: 0.0067 - accuracy: 1.0000 - 17ms/epoch - 17ms/step
Epoch 7/100
1/1 - 0s - loss: 0.0088 - accuracy: 1.0000 - 18ms/epoch - 18ms/step
Epoch 8/100
1/1 - 0s - loss: 0.0069 - accuracy: 1.0000 - 18ms/epoch - 18ms/step
Epoch 9/100
1/1 - 0s - loss: 0.0133 - accuracy: 1.0000 - 19ms/epoch - 19ms/step
Epoch 10/100
1/1 - 0s - loss: 0.0083 - accuracy: 0.8889 - 18ms/epoch - 18ms/step
Epoch 11/100
1/1 - 0s - loss: 0.0056 - accuracy: 0.8889 - 18ms/epoch - 18ms/step
Epoch 12/100
1/1 - 0s - loss: 0.0108 - accuracy: 1.0000 - 19ms/epoch - 19ms/step
Epoch 13/100
1/1 - 0s - loss: 0.0062 

In [92]:
df1 = df.copy()
to_predict = df.tail(6)
to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)
to_predict

<ipython-input-92-6917829a0771>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)


N01  N02  N03  N04  N05  N06
91    5   27   30   41   42    2
92    3   36   38   42   48    6
93    1   12   14   20   31    4
94   13   16   18   27   30    6
95   31   32   34   39   49    6

In [93]:
to_predict = np.array(to_predict)
to_predict

array([[ 5, 27, 30, 41, 42,  2],
       [ 3, 36, 38, 42, 48,  6],
       [ 1, 12, 14, 20, 31,  4],
       [13, 16, 18, 27, 30,  6],
       [31, 32, 34, 39, 49,  6]])

In [94]:
scaled_to_predict = scaler.transform(to_predict)

In [95]:
y_pred = model.predict(np.array([scaled_to_predict]))
print("The predicted numbers in the last lottery game are:", scaler.inverse_transform(y_pred).astype(int)[0])

1/1 [==============================] - 0s 22ms/step
The predicted numbers in the last lottery game are: [ 1  8 10 26 37  2]


In [96]:
prediction = df.tail(1)
prediction = np.array(prediction)
print("The actual numbers in the last lottery game were:", prediction[0])

The actual numbers in the last lottery game were: [ 1  8 11 26 37  2]


In [98]:
temp = np.array(scaler.inverse_transform(y_pred).astype(int)[0])
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("winners:", duplicates)
print(len(duplicates)/6)

winners: [ 1  2  8 26 37]
0.8333333333333334


# Predict the next set of numbers

In [99]:
next = df.copy()
next = next.tail((window_length))
next

N01  N02  N03  N04  N05  N06
92    3   36   38   42   48    6
93    1   12   14   20   31    4
94   13   16   18   27   30    6
95   31   32   34   39   49    6
96    1    8   11   26   37    2

In [100]:
next = np.array(next)
next

array([[ 3, 36, 38, 42, 48,  6],
       [ 1, 12, 14, 20, 31,  4],
       [13, 16, 18, 27, 30,  6],
       [31, 32, 34, 39, 49,  6],
       [ 1,  8, 11, 26, 37,  2]])

In [101]:
x_next = scaler.transform(next)
x_next

next_Date = '2023-12-01 Evening';

In [103]:
y_next_pred = model.predict(np.array([x_next]))
print("The predicted numbers for the lottery game which will take place on",next_Date, "are (without rounding up):\n", scaler.inverse_transform(y_next_pred).astype(int)[0])

print("\n")
temp = np.array(scaler.inverse_transform(y_next_pred).astype(int)[0])
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("without rounding up")
print("winners:", duplicates)
print(len(duplicates)/6)

1/1 [==============================] - 0s 32ms/step
The predicted numbers for the lottery game which will take place on 2023-12-01 Evening are (without rounding up):
 [ 2 11 16 23 34  1]


without rounding up
winners: [ 1  2 11]
0.5


In [104]:
y_next_pred = model.predict(np.array([x_next]))
print("The predicted numbers for the lottery game which will take place on",next_Date, "are (with rounding up):\n", scaler.inverse_transform(y_next_pred).astype(int)[0]+1)

1/1 [==============================] - 0s 29ms/step
The predicted numbers for the lottery game which will take place on 2023-12-01 Evening are (with rounding up):
 [ 3 12 17 24 35  2]


In [105]:
temp = np.array(scaler.inverse_transform(y_next_pred).astype(int)[0]+1)
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("with rounding up")
print("winners:", duplicates)
print(len(duplicates)/20)

with rounding up
winners: [2]
0.05


In [110]:
to_predict_next = df.tail(5)
to_predict_next = np.array(to_predict_next)
to_predict_next

array([[ 3, 36, 38, 42, 48,  6],
       [ 1, 12, 14, 20, 31,  4],
       [13, 16, 18, 27, 30,  6],
       [31, 32, 34, 39, 49,  6],
       [ 1,  8, 11, 26, 37,  2]])

In [111]:
scaled_to_predict_next = scaler.transform(to_predict_next)
y_pred_next = model.predict(np.array([scaled_to_predict_next]))
print("The predicted numbers for the next draw are:\n", scaler.inverse_transform(y_pred_next).astype(int)[0])

1/1 [==============================] - 0s 37ms/step
The predicted numbers for the next draw are:
 [ 2 11 16 23 34  1]
