<a href="https://colab.research.google.com/github/Snowdenstyll/keno/blob/main/Keno_Lottery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("/content/2023.csv")

In [3]:
df.head()

PlayDate AP  N01  N02  N03  N04  N05  N06  N07  N08  ...  N11  N12  N13  \
0  2023-01-01  A    3    7    9   14   19   21   22   30  ...   38   39   43   
1  2023-01-01  P    4    5   10   11   13   18   19   27  ...   37   41   43   
2  2023-01-02  A    2    9   11   14   21   24   29   38  ...   47   48   50   
3  2023-01-02  P    2    3    4    7   15   24   25   30  ...   44   47   48   
4  2023-01-03  A    5    6    7   10   21   22   24   25  ...   34   39   43   

   N14  N15  N16  N17  N18  N19  N20  
0   53   54   56   61   64   65   69  
1   44   47   48   55   58   63   70  
2   57   58   59   60   61   66   70  
3   53   54   56   58   60   66   68  
4   45   46   48   49   57   59   65  

[5 rows x 22 columns]

In [4]:
df.tail()

PlayDate AP  N01  N02  N03  N04  N05  N06  N07  N08  ...  N11  N12  \
674  2023-12-05  A    6    7    8   18   20   21   24   25  ...   37   39   
675  2023-12-05  P    3    9   11   13   18   20   23   25  ...   44   50   
676  2023-12-06  A    5    6   10   11   14   18   21   22  ...   38   46   
677  2023-12-06  P    2    7   11   16   17   20   24   25  ...   40   41   
678  2023-12-07  A    7   10   15   17   19   25   28   31  ...   45   49   

     N13  N14  N15  N16  N17  N18  N19  N20  
674   44   50   55   56   58   60   61   66  
675   51   52   54   56   58   62   63   66  
676   47   48   49   59   65   67   68   69  
677   43   44   49   52   55   56   60   61  
678   51   56   58   60   61   64   65   67  

[5 rows x 22 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 679 entries, 0 to 678
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   PlayDate  679 non-null    object
 1   AP        679 non-null    object
 2   N01       679 non-null    int64 
 3   N02       679 non-null    int64 
 4   N03       679 non-null    int64 
 5   N04       679 non-null    int64 
 6   N05       679 non-null    int64 
 7   N06       679 non-null    int64 
 8   N07       679 non-null    int64 
 9   N08       679 non-null    int64 
 10  N09       679 non-null    int64 
 11  N10       679 non-null    int64 
 12  N11       679 non-null    int64 
 13  N12       679 non-null    int64 
 14  N13       679 non-null    int64 
 15  N14       679 non-null    int64 
 16  N15       679 non-null    int64 
 17  N16       679 non-null    int64 
 18  N17       679 non-null    int64 
 19  N18       679 non-null    int64 
 20  N19       679 non-null    int64 
 21  N20       679 no

In [6]:
df.describe()

N01         N02         N03         N04         N05         N06  \
count  679.000000  679.000000  679.000000  679.000000  679.000000  679.000000   
mean     3.119293    6.416789    9.793814   13.061856   16.645066   20.248895   
std      2.364729    3.356640    4.114715    4.830368    5.368083    5.766721   
min      1.000000    2.000000    3.000000    4.000000    5.000000    8.000000   
25%      1.000000    4.000000    7.000000    9.000000   13.000000   16.000000   
50%      2.000000    6.000000    9.000000   12.000000   16.000000   20.000000   
75%      4.000000    8.000000   12.000000   16.000000   20.000000   24.000000   
max     15.000000   19.000000   27.000000   28.000000   35.000000   43.000000   

              N07         N08         N09         N10         N11         N12  \
count  679.000000  679.000000  679.000000  679.000000  679.000000  679.000000   
mean    23.681885   27.179676   30.618557   33.898380   37.269514   40.522828   
std      5.960946    5.898862    5.998304    5.986956    6.060375    6.128106   
min     11.000000   12.000000   14.000000   17.000000   20.000000   23.000000   
25%     20.000000   23.000000   26.000000   30.000000   33.000000   36.000000   
50%     23.000000   27.000000   31.000000   34.000000   37.000000   40.000000   
75%     27.500000   31.000000   35.000000   37.000000   41.000000   45.000000   
max     46.000000   47.000000   49.000000   51.000000   54.000000   57.000000   

              N13         N14         N15         N16         N17         N18  \
count  679.000000  679.000000  679.000000  679.000000  679.000000  679.000000   
mean    43.938144   47.500736   50.824742   53.992636   57.415317   60.712813   
std      5.932686    5.665680    5.490155    5.230521    4.726577    4.357714   
min     25.000000   31.000000   35.000000   37.000000   39.000000   40.000000   
25%     40.000000   44.000000   47.000000   50.500000   54.000000   58.000000   
50%     44.000000   48.000000   51.000000   55.000000   58.000000   61.000000   
75%     48.000000   52.000000   55.000000   58.000000   61.000000   64.000000   
max     58.000000   61.000000   62.000000   64.000000   67.000000   68.000000   

              N19         N20  
count  679.000000  679.000000  
mean    64.108984   67.645066  
std      3.687245    2.525814  
min     46.000000   58.000000  
25%     62.000000   66.000000  
50%     65.000000   68.000000  
75%     67.000000   70.000000  
max     69.000000   70.000000

In [7]:
df.drop(['PlayDate', 'AP'], axis=1, inplace=True)

In [8]:
df.head()

N01  N02  N03  N04  N05  N06  N07  N08  N09  N10  N11  N12  N13  N14  N15  \
0    3    7    9   14   19   21   22   30   32   34   38   39   43   53   54   
1    4    5   10   11   13   18   19   27   31   32   37   41   43   44   47   
2    2    9   11   14   21   24   29   38   40   42   47   48   50   57   58   
3    2    3    4    7   15   24   25   30   38   39   44   47   48   53   54   
4    5    6    7   10   21   22   24   25   26   32   34   39   43   45   46   

   N16  N17  N18  N19  N20  
0   56   61   64   65   69  
1   48   55   58   63   70  
2   59   60   61   66   70  
3   56   58   60   66   68  
4   48   49   57   59   65

In [9]:
scaler = StandardScaler().fit(df.values)
transformed_dataset = scaler.transform(df.values)
transformed_df = pd.DataFrame(data=transformed_dataset, index=df.index)

In [10]:
transformed_df.head()

0         1         2         3         4         5         6   \
0 -0.050484  0.173876 -0.193063  0.194361  0.439015  0.130344 -0.282359   
1  0.372709 -0.422397  0.050146 -0.427167 -0.679526 -0.390266 -0.786006   
2 -0.473677  0.770150  0.293356  0.194361  0.811862  0.650954  0.892817   
3 -0.473677 -1.018670 -1.409110 -1.255872 -0.306679  0.650954  0.221288   
4  0.795902 -0.124260 -0.679482 -0.634344  0.811862  0.303881  0.053406   

         7         8         9         10        11        12        13  \
0  0.478466  0.230475  0.016986  0.120624 -0.248682 -0.158248  0.971343   
1 -0.030482  0.063639 -0.317320 -0.044504  0.077924 -0.158248 -0.618340   
2  1.835659  1.565169  1.354209  1.606775  1.221044  1.022526  1.677869   
3  0.478466  1.231496  0.852751  1.111391  1.057741  0.685162  0.971343   
4 -0.369780 -0.770545 -0.317320 -0.539888 -0.248682 -0.158248 -0.441709   

         14        15        16        17        18        19  
0  0.578781  0.384062  0.758969  0.754894  0.241826  0.536830  
1 -0.697168 -1.146550 -0.511384 -0.622990 -0.300984  0.933034  
2  1.307895  0.958041  0.547244  0.065952  0.513232  0.933034  
3  0.578781  0.384062  0.123792 -0.163696  0.513232  0.140626  
4 -0.879447 -1.146550 -1.781738 -0.852637 -1.386604 -1.047985

In [11]:
# All our games
number_of_rows = df.values.shape[0]
number_of_rows

679

In [12]:
# Amount of games we need to take into consideration for prediction
window_length = 6
window_length

6

In [13]:
# Balls counts
number_of_features = df.values.shape[1]
number_of_features

20

In [14]:
X = np.empty([ number_of_rows - window_length, window_length, number_of_features], dtype=float)
X

array([[[6.93600522e-310, 4.72290146e-310, 0.00000000e+000, ...,
         2.15343452e-319, 2.15358274e-319, 2.15373096e-319],
        [2.15387918e-319, 2.15402740e-319, 2.15417562e-319, ...,
         2.15649773e-319, 2.15664595e-319, 2.15679417e-319],
        [2.15694239e-319, 2.15709061e-319, 2.15723883e-319, ...,
         2.15975856e-319, 2.15990678e-319, 2.16005500e-319],
        [2.16020322e-319, 2.16035144e-319, 2.16049966e-319, ...,
         2.16301940e-319, 2.16316762e-319, 2.16331584e-319],
        [2.16346406e-319, 2.16361228e-319, 2.16376050e-319, ...,
         2.16618142e-319, 2.16632964e-319, 2.16647786e-319],
        [2.16662608e-319, 2.16677430e-319, 2.16692252e-319, ...,
         2.16934344e-319, 2.16949166e-319, 2.16963988e-319]],

       [[2.16978810e-319, 2.16993632e-319, 2.17008454e-319, ...,
         2.17260427e-319, 2.17270308e-319, 2.17280190e-319],
        [2.17290071e-319, 2.17304893e-319, 2.17319715e-319, ...,
         2.17581570e-319, 2.17591451e-319, 2.176013

In [15]:
y = np.empty([ number_of_rows - window_length, number_of_features], dtype=float)
y

array([[6.93600522e-310, 6.93600522e-310, 4.72290148e-310, ...,
        6.93600418e-310, 4.94065646e-324, 2.12199579e-314],
       [8.48798316e-314, 1.27319747e-313, 6.01346930e-154, ...,
        4.72271383e-310, 6.01346930e-154, 3.18299369e-313],
       [6.15378779e-313, 4.72271383e-310, 6.93593908e-310, ...,
        9.97338022e-313, 1.37929726e-312, 1.17553412e-047],
       ...,
       [1.83584540e+000, 5.54571285e+000, 1.25977950e-001, ...,
        2.70624305e+000, 1.83584540e+000, 6.99637559e+000],
       [1.25977950e-001, 1.83584540e+000, 6.99637559e+000, ...,
        5.54571285e+000, 2.15766407e+001, 1.25977950e-001],
       [1.25977950e-001, 1.83584540e+000, 1.25977950e-001, ...,
        5.54571285e+000, 1.83584540e+000, 1.83584540e+000]])

In [16]:
for i in range(0, number_of_rows-window_length):
    X[i] = transformed_df.iloc[i : i+window_length, 0 : number_of_features]
    y[i] = transformed_df.iloc[i+window_length : i+window_length+1, 0 : number_of_features]

In [17]:
X.shape

(673, 6, 20)

In [18]:
y.shape

(673, 20)

In [19]:
X[0]

array([[-0.05048402,  0.17387641, -0.19306312,  0.19436117,  0.43901516,
         0.13034414, -0.28235873,  0.47846567,  0.23047542,  0.01698609,
         0.12062365, -0.24868211, -0.15824805,  0.97134289,  0.57878116,
         0.38406183,  0.75896908,  0.75489354,  0.24182637,  0.53682995],
       [ 0.37270918, -0.42239673,  0.05014626, -0.42716741, -0.67952628,
        -0.39026569, -0.7860056 , -0.03048189,  0.06363873, -0.31731977,
        -0.04450429,  0.0779236 , -0.15824805, -0.61834013, -0.69716822,
        -1.14654996, -0.51138426, -0.6229901 , -0.3009839 ,  0.9330338 ],
       [-0.47367722,  0.77014955,  0.29335565,  0.19436117,  0.8118623 ,
         0.65095398,  0.8928173 ,  1.83565914,  1.56516886,  1.3542095 ,
         1.60677514,  1.22104359,  1.02252586,  1.67786868,  1.3078951 ,
         0.95804125,  0.54724352,  0.06595172,  0.51323151,  0.9330338 ],
       [-0.47367722, -1.01866987, -1.40911003, -1.2558722 , -0.30667913,
         0.65095398,  0.22128814,  0.47846567,  

In [20]:
X[1]

array([[ 0.37270918, -0.42239673,  0.05014626, -0.42716741, -0.67952628,
        -0.39026569, -0.7860056 , -0.03048189,  0.06363873, -0.31731977,
        -0.04450429,  0.0779236 , -0.15824805, -0.61834013, -0.69716822,
        -1.14654996, -0.51138426, -0.6229901 , -0.3009839 ,  0.9330338 ],
       [-0.47367722,  0.77014955,  0.29335565,  0.19436117,  0.8118623 ,
         0.65095398,  0.8928173 ,  1.83565914,  1.56516886,  1.3542095 ,
         1.60677514,  1.22104359,  1.02252586,  1.67786868,  1.3078951 ,
         0.95804125,  0.54724352,  0.06595172,  0.51323151,  0.9330338 ],
       [-0.47367722, -1.01866987, -1.40911003, -1.2558722 , -0.30667913,
         0.65095398,  0.22128814,  0.47846567,  1.2314955 ,  0.85275072,
         1.11139131,  1.05774074,  0.68516188,  0.97134289,  0.57878116,
         0.38406183,  0.12379241, -0.16369555,  0.51323151,  0.14062611],
       [ 0.79590237, -0.12426016, -0.67948188, -0.63434361,  0.8118623 ,
         0.30388075,  0.05340585, -0.36978025, -

In [21]:
y[0]

array([-0.89687041, -0.7205333 , -1.16590065, -1.048696  ,  0.06616801,
        0.30388075, -0.11447644, -0.20013107, -0.43687131, -0.31731977,
        0.2857516 ,  0.0779236 ,  0.01043394, -0.44170868,  0.03194571,
        0.38406183,  1.1824202 ,  0.75489354,  1.05604178,  0.53682995])

In [22]:
y[1]

array([ 2.06548197e+00,  7.70149549e-01,  2.72544946e+00,  2.68047553e+00,
        1.93040373e+00,  1.51863704e+00,  1.06069959e+00,  6.48114851e-01,
        7.30985459e-01,  3.51291938e-01,  2.85751596e-01,  1.22104359e+00,
        8.53843872e-01,  6.18079997e-01,  3.96502680e-01,  1.40888420e-03,
        1.23792410e-01, -3.93342826e-01, -3.00983899e-01, -1.44418928e+00])

In [23]:
# Recurrent Neural Netowrk (RNN) with Long Short Term Memory (LSTM)
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, Dropout
batch_size = 100

In [24]:
# Initialising the RNN
model = Sequential()
# Adding the input layer and the LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a first Dropout layer
model.add(Dropout(0.2))
# Adding a second LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a second Dropout layer
model.add(Dropout(0.2))
# Adding a third LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a fourth LSTM layer
model.add(Bidirectional(LSTM(256,
                        input_shape = (window_length, number_of_features),
                        return_sequences = False)))
# Adding a fourth Dropout layer
model.add(Dropout(0.2))
# Adding the first output layer
model.add(Dense(70))
# Adding the last output layer
model.add(Dense(number_of_features))

In [25]:
from tensorflow import keras
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.0001), loss ='mse', metrics=['accuracy'])

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9, random_state=90)

# Train the model
history = model.fit(X, y, batch_size=100, epochs=1000, verbose=2)
#history = model.fit(X_train, y_train, batch_size=100, epochs=600, verbose=2)


Epoch 1/1000
7/7 - 23s - loss: 1.0016 - accuracy: 0.0609 - 23s/epoch - 3s/step
Epoch 2/1000
7/7 - 0s - loss: 0.9994 - accuracy: 0.0505 - 127ms/epoch - 18ms/step
Epoch 3/1000
7/7 - 0s - loss: 0.9973 - accuracy: 0.0624 - 110ms/epoch - 16ms/step
Epoch 4/1000
7/7 - 0s - loss: 0.9958 - accuracy: 0.0698 - 95ms/epoch - 14ms/step
Epoch 5/1000
7/7 - 0s - loss: 0.9946 - accuracy: 0.0609 - 105ms/epoch - 15ms/step
Epoch 6/1000
7/7 - 0s - loss: 0.9927 - accuracy: 0.0624 - 105ms/epoch - 15ms/step
Epoch 7/1000
7/7 - 0s - loss: 0.9908 - accuracy: 0.0684 - 96ms/epoch - 14ms/step
Epoch 8/1000
7/7 - 0s - loss: 0.9894 - accuracy: 0.0847 - 104ms/epoch - 15ms/step
Epoch 9/1000
7/7 - 0s - loss: 0.9872 - accuracy: 0.0892 - 106ms/epoch - 15ms/step
Epoch 10/1000
7/7 - 0s - loss: 0.9854 - accuracy: 0.0743 - 122ms/epoch - 17ms/step
Epoch 11/1000
7/7 - 0s - loss: 0.9831 - accuracy: 0.0743 - 102ms/epoch - 15ms/step
Epoch 12/1000
7/7 - 0s - loss: 0.9825 - accuracy: 0.0817 - 109ms/epoch - 16ms/step
Epoch 13/1000
7/7 

In [27]:
loss, accuracy = model.evaluate(X, y, verbose=1)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

22/22 [==============================] - 3s 11ms/step - loss: 0.0052 - accuracy: 0.8915
Test Loss: 0.005162391811609268, Test Accuracy: 0.891530454158783


In [28]:
#history = model.fit(X_train, y_train, batch_size=50, epochs=100, verbose=2)
#history = model.fit(X_train, y_train, batch_size=50, epochs=100, verbose=2)

In [87]:
df1 = df.copy()
to_predict = df.tail(7)
to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)
to_predict

<ipython-input-87-4d6bef978192>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)


N01  N02  N03  N04  N05  N06  N07  N08  N09  N10  N11  N12  N13  N14  \
672    7    9   12   14   16   18   20   24   25   30   34   44   45   47   
673    1    3    6    7   16   20   31   35   38   42   49   50   51   52   
674    6    7    8   18   20   21   24   25   32   36   37   39   44   50   
675    3    9   11   13   18   20   23   25   37   41   44   50   51   52   
676    5    6   10   11   14   18   21   22   25   29   38   46   47   48   
677    2    7   11   16   17   20   24   25   27   30   40   41   43   44   

     N15  N16  N17  N18  N19  N20  
672   49   51   54   59   64   70  
673   53   55   56   57   63   64  
674   55   56   58   60   61   66  
675   54   56   58   62   63   66  
676   49   59   65   67   68   69  
677   49   52   55   56   60   61

In [88]:
to_predict = np.array(to_predict)
to_predict

array([[ 7,  9, 12, 14, 16, 18, 20, 24, 25, 30, 34, 44, 45, 47, 49, 51,
        54, 59, 64, 70],
       [ 1,  3,  6,  7, 16, 20, 31, 35, 38, 42, 49, 50, 51, 52, 53, 55,
        56, 57, 63, 64],
       [ 6,  7,  8, 18, 20, 21, 24, 25, 32, 36, 37, 39, 44, 50, 55, 56,
        58, 60, 61, 66],
       [ 3,  9, 11, 13, 18, 20, 23, 25, 37, 41, 44, 50, 51, 52, 54, 56,
        58, 62, 63, 66],
       [ 5,  6, 10, 11, 14, 18, 21, 22, 25, 29, 38, 46, 47, 48, 49, 59,
        65, 67, 68, 69],
       [ 2,  7, 11, 16, 17, 20, 24, 25, 27, 30, 40, 41, 43, 44, 49, 52,
        55, 56, 60, 61]])

In [90]:
scaled_to_predict = scaler.transform(to_predict)

In [91]:
y_pred = model.predict(np.array([scaled_to_predict]))
print("The predicted numbers in the last lottery game are:", scaler.inverse_transform(y_pred).astype(int)[0])

1/1 [==============================] - 0s 35ms/step
The predicted numbers in the last lottery game are: [ 7 10 15 17 19 25 28 31 37 39 44 49 51 55 57 60 61 63 64 66]


In [92]:
prediction = df.tail(1)
prediction = np.array(prediction)
print("The actual numbers in the last lottery game were:", prediction[0])

The actual numbers in the last lottery game were: [ 7 10 15 17 19 25 28 31 37 39 45 49 51 56 58 60 61 64 65 67]


In [93]:
temp = np.array(scaler.inverse_transform(y_pred).astype(int)[0])
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("winners:", duplicates)
print(len(duplicates)/20)

winners: [ 7 10 15 17 19 25 28 31 37 39 49 51 60 61 64]
0.75


# Predict the next set of numbers

In [35]:
next = df.copy()
next = next.tail((window_length))
next

N01  N02  N03  N04  N05  N06  N07  N08  N09  N10  N11  N12  N13  N14  \
673    1    3    6    7   16   20   31   35   38   42   49   50   51   52   
674    6    7    8   18   20   21   24   25   32   36   37   39   44   50   
675    3    9   11   13   18   20   23   25   37   41   44   50   51   52   
676    5    6   10   11   14   18   21   22   25   29   38   46   47   48   
677    2    7   11   16   17   20   24   25   27   30   40   41   43   44   
678    7   10   15   17   19   25   28   31   37   39   45   49   51   56   

     N15  N16  N17  N18  N19  N20  
673   53   55   56   57   63   64  
674   55   56   58   60   61   66  
675   54   56   58   62   63   66  
676   49   59   65   67   68   69  
677   49   52   55   56   60   61  
678   58   60   61   64   65   67

In [36]:
next = np.array(next)
next

array([[ 1,  3,  6,  7, 16, 20, 31, 35, 38, 42, 49, 50, 51, 52, 53, 55,
        56, 57, 63, 64],
       [ 6,  7,  8, 18, 20, 21, 24, 25, 32, 36, 37, 39, 44, 50, 55, 56,
        58, 60, 61, 66],
       [ 3,  9, 11, 13, 18, 20, 23, 25, 37, 41, 44, 50, 51, 52, 54, 56,
        58, 62, 63, 66],
       [ 5,  6, 10, 11, 14, 18, 21, 22, 25, 29, 38, 46, 47, 48, 49, 59,
        65, 67, 68, 69],
       [ 2,  7, 11, 16, 17, 20, 24, 25, 27, 30, 40, 41, 43, 44, 49, 52,
        55, 56, 60, 61],
       [ 7, 10, 15, 17, 19, 25, 28, 31, 37, 39, 45, 49, 51, 56, 58, 60,
        61, 64, 65, 67]])

In [37]:
x_next = scaler.transform(next)
x_next

next_Date = '2023-12-01 Evening';

In [38]:
y_next_pred = model.predict(np.array([x_next]))
print("The predicted numbers for the lottery game which will take place on",next_Date, "are (without rounding up):\n", scaler.inverse_transform(y_next_pred).astype(int)[0])

print("\n")
temp = np.array(scaler.inverse_transform(y_next_pred).astype(int)[0])
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("without rounding up")
print("winners:", duplicates)
print(len(duplicates)/20)

1/1 [==============================] - 3s 3s/step
The predicted numbers for the lottery game which will take place on 2023-12-01 Evening are (without rounding up):
 [ 3  5  7  9 10 17 21 25 28 29 33 36 41 44 47 50 52 57 57 65]


without rounding up
winners: [ 7 10 17 25 28 57 65]
0.35


In [39]:
y_next_pred = model.predict(np.array([x_next]))
print("The predicted numbers for the lottery game which will take place on",next_Date, "are (with rounding up):\n", scaler.inverse_transform(y_next_pred).astype(int)[0]+1)

1/1 [==============================] - 0s 37ms/step
The predicted numbers for the lottery game which will take place on 2023-12-01 Evening are (with rounding up):
 [ 4  6  8 10 11 18 22 26 29 30 34 37 42 45 48 51 53 58 58 66]


In [40]:
temp = np.array(scaler.inverse_transform(y_next_pred).astype(int)[0]+1)
combined_array = np.concatenate((temp, np.array(prediction[0])))
winning_numbers = np.bincount(combined_array)
winners = np.unique(combined_array)

uniques, uniq_idx, counts = np.unique(combined_array,return_index=True,return_counts=True)
duplicates = combined_array[ uniq_idx[counts>=2] ]  # <--- Get duplicates

print("with rounding up")
print("winners:", duplicates)
print(len(duplicates)/20)

with rounding up
winners: [10 37 45 51 58]
0.25


In [98]:
to_predict_next = df.tail(6)
to_predict_next = np.array(to_predict_next)
to_predict_next

array([[ 1,  3,  6,  7, 16, 20, 31, 35, 38, 42, 49, 50, 51, 52, 53, 55,
        56, 57, 63, 64],
       [ 6,  7,  8, 18, 20, 21, 24, 25, 32, 36, 37, 39, 44, 50, 55, 56,
        58, 60, 61, 66],
       [ 3,  9, 11, 13, 18, 20, 23, 25, 37, 41, 44, 50, 51, 52, 54, 56,
        58, 62, 63, 66],
       [ 5,  6, 10, 11, 14, 18, 21, 22, 25, 29, 38, 46, 47, 48, 49, 59,
        65, 67, 68, 69],
       [ 2,  7, 11, 16, 17, 20, 24, 25, 27, 30, 40, 41, 43, 44, 49, 52,
        55, 56, 60, 61],
       [ 7, 10, 15, 17, 19, 25, 28, 31, 37, 39, 45, 49, 51, 56, 58, 60,
        61, 64, 65, 67]])

In [99]:
scaled_to_predict_next = scaler.transform(to_predict_next)
y_pred_next = model.predict(np.array([scaled_to_predict_next]))
print("The predicted numbers for the next draw are:\n", scaler.inverse_transform(y_pred_next).astype(int)[0])

1/1 [==============================] - 0s 21ms/step
The predicted numbers for the next draw are:
 [ 3  5  7  9 10 17 21 25 28 29 33 36 41 44 47 50 52 57 57 65]
